### PR TITLE
Add revert to backup option to file menu

### PR DESCRIPTION
**Pull request by taylorobyen**
This addresses #3427 

`Load Backup` button to File menu on the main window
image
When loading a backup the relative time it was taken is displayed
image

### CODE REVIEW

**Comment by dae** [comment]
Sorry Taylor, I appear to have made a thinko. When I suggested mentioning the previous backup time, it was because I was assuming we'd be automatically selecting the most-recent backup. Giving the user a list of backups is more flexible, and it makes the time shown somewhat redundant. I was originally going to ask you to move the "x minutes ago" code into Rust so it can be shared across the clients, but since it's a bit redundant, the fastest way to get the PR over the line would be to change the message to show the backup filename instead of a relative time. Does that work for you?

**Comment by taylorobyen** [comment]
No worries Damien, I've switched it to be filename as requested. 👍

**Review by dae — COMMENTED** [review]
(will put this through myself; was a pending suggestion that I forgot to send)

**Comment by dae** [comment]
Thanks Taylor!

**Pull request merged**
