### PR TITLE
Allow addons to disable the progress bar when the have their own

### PR DESCRIPTION
**Pull request by evandrocoan**
https://github.com/kelciour/awesometts-anki-addon/pull/24 - Disables the Anki progress bar before using our progress bar

### CODE REVIEW

**Comment by dae** [comment]
What Anki code is the add-on calling that is displaying the progress bar?

**Comment by evandrocoan** [comment]
`browser.model.beginReset()/endReset()`: https://github.com/kelciour/awesometts-anki-addon/pull/24/files

**Comment by dae** [comment]
Rather than add a hack to disable the progress bar of routines that create a progress bar, wouldn't it be clearer to modify the add-on to not call beginReset/endReset? It can just call .reset() at the end to trigger a browser refresh

**Comment by evandrocoan** [comment]
I do not know why it was calling these things, or that it could just call `.reset()` at the end. I will update the addons accordingly.

**Pull request closed without merging**
