### PR TITLE
Allow searching for missing custom data properties

### PR DESCRIPTION
**Pull request by abdnh**
This extends `prop:cdn` to support searching for missing properties using something like `prop:cdn:r=none`.

Context: https://forums.ankiweb.net/t/more-flags-add-flags-with-custom-names-and-colors/33661/4

### CODE REVIEW

**Comment by dae** [comment]
Hmm. If we introduce a way to search for strings as well in the future (https://github.com/ankitects/anki/issues/2627), this would presumably need to be done there too. What do you think about having some separate query like has-cd:foo? Hopefully it would make things a bit simpler. Apologies for only thinking about this after you'd already done the work. :-(

**Comment by abdnh** [comment]
> What do you think about having some separate query like has-cd:foo?

Sounds reasonable. Will look into that.

**Comment by abdnh** [comment]
I implemented this using yet another SQL function. Should we maybe add a general `extract_custom_data` function and remove `extract_custom_data_number`?

**Comment by dae** [comment]
Code changes look good.

I'm ok with using a single extract_custom_data function that just returns strings. It would lead to possibly confusing ordering on values that were supposed to be numeric but weren't, but that's probably not a big deal. I think we'll need to keep the cdn search though, as we'll get different results with numbers and strings:

sqlite> select 1 < 3;
1 < 3 = 1
sqlite> select '1' < 3;
'1' < 3 = 0

Maybe cdn could be rewritten to do the equivalent of this?

sqlite> select cast('1' as float) < 3;
cast('1' as float) < 3 = 1

**Pull request merged**
