### PR TITLE
Bug/next day at

### PR DESCRIPTION
**Pull request by ig3**
If I understand correctly, the new Rust next_day_at is inconsistent with the current Python _dayCutoff and because the value is exposed to the Python code as self.dayCutoff in schedv2.py, these differences might be significant. Also, the DST transitions are not handled correctly.

This PR provides a set of tests for next_day_at that demonstrate the problems, as I understand them. The tests are replete with prints which should be removed and I would prefer creating timezone aware datetimes with specified TZ without setting the TZ environment variable, but I don't know how to do this. So these tests are not ideal, but I think the suffice to demonstrate the problems.

### CODE REVIEW

**Comment by ig3** [comment]
And the final assert is just so I can see the output if none of the other assertions fail. It should be removed too.

**Comment by dae** [comment]
Hi Ian,

Thanks again for your extensive testing. I've pushed a fix for the issue where the rollover time was off by a day before the rollover for the day had passed.

I am not too concerned about being off by an hour the two times a year DST changes. For one, the rollover hour is supposed to be set to a time you're usually sleeping, where +/- one hour should usually make no difference. Furthermore, the rollover time is recalculated each time sched.reset() is called, so there is a decent chance the rollover time will have been adjusted prior to it being reached anyway.

The reason I went for fixed offsets instead of timezone names is because of consistency concerns. We can't expect all clients to be updated in lockstep, and users may be running older builds. If we calculated the UTC offsets dynamically, there is a risk that different clients would come up with different results, which can result in cards being unburied when they shouldn't be, the daily counts being reset and so on.

**Comment by dae** [comment]
Sorry, that wasn't clear - I was referring to the fact that timezone rules change over time, thus an older client may not be aware of the latest changes and may produce a different result.

**Comment by ig3** [comment]
Thanks again for the prompt response. Your update looks good to me. I agree that the one hour errors on the days of DST transition are minor and consistency is important. I'm far from having a sense of the broader implications of these changes and trust your judgment on that. Now I will look forward to the new code being enabled.

**Comment by dae** [comment]
Hi Ian,

These latest fixes are in the AnkiMobile beta that was released today, and updated instructions are on https://anki.tenderapp.com/kb/anki-ecosystem/timezone-handling-changes

I won't be able to make this the default until AD supports it as well, so once it's had a bit more testing I'll reach out to the AD devs.

**Comment by dae** [comment]
In case you missed it, the Python code for calculating the the timezone offset in .19 was broken - it should be addressed in the .20 betas.

**Pull request closed without merging**
