### PR TITLE
Quote $PREFIX properly for paths with spaces

### PR DESCRIPTION
**Pull request by lolilolicon**

### CODE REVIEW

**Comment by dae** [comment]
Thanks! Please sort out the failing test, then I'll merge this in.

**Comment by lolilolicon** [comment]
No idea why the tests are failing. It's a very simple change...

**Comment by dae** [comment]
https://github.com/ankitects/anki/blob/main/docs/contributing.md#license

**Comment by lolilolicon** [comment]
Hello, is this OK to merge now?

**Comment by dae** [comment]
Yep, thanks!

**Pull request merged**
