### PR TITLE
Feat/Easy Days

### LINKED ISSUE #3116: Integrations of Load balance & Easy days
These two features require Anki to maintain a record of how many cards are due on each day.

As an initial idea, we may maintain this record in `StateContext`.

### PR DESCRIPTION
**Pull request by L-M-Sherlock**
close #3116

Help and suggestion wanted:
1. How to convert the interval into weekday when considering the `next day starts at`?
2. Where is a good place to store `easy_days_percentages`?
3. Should we make it configurable in preset-level? It's annoying to set easy days in preset-level if the user has a lot of preset.

---

2024-10-08 update: 

image

### CODE REVIEW

**Comment by brishtibheja** [comment]
Dae, if you don't want to make it global can we have something like the daily limits, with easy days being configurable both for the preset and for all the presets? Or a "Apply globally" setting? Just throwing two ideas out there. I personally think preset-level is too niche that it's better done if there's enough demand.

**Comment by Expertium** [comment]
"Apply to all presets" sounds good

**Comment by dae** [comment]
I think it's a fair assumption that global configuration would meet the needs of the majority of users. But if it's only global, it will prevent users from doing things like prioritizing certain subjects on certain days. And if we have both global and preset, it's a more complicated interface.

My preference would be on just making it a preset option. This is a setting that doesn't make sense to change frequently, and for users moving forward, they can clone new presets from their old ones to avoid having to set it again. And we can provide a short debug console command for existing power users to update all their presets at once.

> It's annoying to set easy days in preset-level if the user has a lot of preset.

You could use the same argument for any of the other preset settings we currently have. If we really want to solve that, perhaps a better way to do so would be to have presets indicate which of their options should override some configurable global defaults. But that's a rather involved change, and not specific to this PR.

> How to convert the interval into weekday when considering the next day starts at?

IntervalKind::maybe_as_days() is used in the scheduling code to determine the number of days from the current day. If you know the current day of the week, and the due day the card will end up as, you can see how many it is from timing_today.days_elapsed, and add that span to the current day of the week.

> Where is a good place to store easy_days_percentages?

That's where I would have put it.

**Comment by L-M-Sherlock** [comment]
I don't know how to fix following errors. Help wanted.

```
=================================== FAILURES ===================================
__________________________________ test_apkg ___________________________________

    def test_apkg():
        col = getEmptyCol()
        apkg = str(os.path.join(testDir, "support", "media.apkg"))
        imp = AnkiPackageImporter(col, apkg)
        assert os.listdir(col.media.dir()) == []
>       imp.run()

pylib/tests/test_importing.py:84: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pylib/anki/importing/apkg.py:51: in run
    Anki2Importer.run(self, importing_v2=suffix == ".anki21")
pylib/anki/importing/anki2.py:49: in run
    self._prepareFiles()
pylib/anki/importing/anki2.py:62: in _prepareFiles
    self.src = Collection(self.file)
pylib/anki/collection.py:151: in __init__
    self.reopen()
pylib/anki/collection.py:292: in reopen
    self._backend.open_collection(
out/pylib/anki/_backend_generated.py:144: in open_collection
    raw_bytes = self._run_command(3, 0, message.SerializeToString())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <anki._backend.RustBackend object at 0x109345100>, service = 3
method = 0
input = b'\nI/var/folders/20/_t6_h0cx4nl1qr58y1km9l740000gn/T/anki_temp/2phxmvfz.anki2\x12I/var/folders/20/_t6_h0cx4nl1qr58y1km9l740000gn/T/anki_temp/2phxmvfz.media\x1aM/var/folders/20/_t6_h0cx4nl1qr58y1km9l740000gn/T/anki_temp/2phxmvfz.media.db2'

    def _run_command(self, service: int, method: int, input: bytes) -> bytes:
        start = time.time()
        try:
            return self._backend.command(service, method, input)
        except Exception as error:
            error_bytes = bytes(error.args[0])
        finally:
            elapsed = time.time() - start
            if current_thread() is main_thread() and elapsed > 0.2:
                print(f"blocked main thread for {int(elapsed*1000)}ms:")
                print("".join(traceback.format_stack()))
    
        err = backend_pb2.BackendError()
        err.ParseFromString(error_bytes)
>       raise backend_exception_to_pylib(err)
E       anki.errors.BackendError: JsonError { info: "decoding deck config: missing field `easyDaysPercentages`" }

pylib/anki/_backend.py:172: BackendError
________________________ test_anki2_diffmodel_templates ________________________

    def test_anki2_diffmodel_templates():
        # different from the above as this one tests only the template text being
        # changed, not the number of cards/fields
        dst = getEmptyCol()
        # import the first version of the model
        col = getUpgradeDeckPath("diffmodeltemplates-1.apkg")
        imp = AnkiPackageImporter(dst, col)
        imp.dupeOnSchemaChange = True  # type: ignore
>       imp.run()

pylib/tests/test_importing.py:108: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pylib/anki/importing/apkg.py:51: in run
    Anki2Importer.run(self, importing_v2=suffix == ".anki21")
pylib/anki/importing/anki2.py:49: in run
    self._prepareFiles()
pylib/anki/importing/anki2.py:62: in _prepareFiles
    self.src = Collection(self.file)
pylib/anki/collection.py:151: in __init__
    self.reopen()
pylib/anki/collection.py:292: in reopen
    self._backend.open_collection(
out/pylib/anki/_backend_generated.py:144: in open_collection
    raw_bytes = self._run_command(3, 0, message.SerializeToString())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <anki._backend.RustBackend object at 0x10cb9a760>, service = 3
method = 0
input = b'\nI/var/folders/20/_t6_h0cx4nl1qr58y1km9l740000gn/T/anki_temp/bhw33mvx.anki2\x12I/var/folders/20/_t6_h0cx4nl1qr58y1km9l740000gn/T/anki_temp/bhw33mvx.media\x1aM/var/folders/20/_t6_h0cx4nl1qr58y1km9l740000gn/T/anki_temp/bhw33mvx.media.db2'

    def _run_command(self, service: int, method: int, input: bytes) -> bytes:
        start = time.time()
        try:
            return self._backend.command(service, method, input)
        except Exception as error:
            error_bytes = bytes(error.args[0])
        finally:
            elapsed = time.time() - start
            if current_thread() is main_thread() and elapsed > 0.2:
                print(f"blocked main thread for {int(elapsed*1000)}ms:")
                print("".join(traceback.format_stack()))
    
        err = backend_pb2.BackendError()
        err.ParseFromString(error_bytes)
>       raise backend_exception_to_pylib(err)
E       anki.errors.BackendError: JsonError { info: "decoding deck config: missing field `easyDaysPercentages`" }

pylib/anki/_backend.py:172: BackendError
______________________________ test_anki2_updates ______________________________

    def test_anki2_updates():
        # create a new empty deck
        dst = getEmptyCol()
        col = getUpgradeDeckPath("update1.apkg")
        imp = AnkiPackageImporter(dst, col)
>       imp.run()

pylib/tests/test_importing.py:127: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pylib/anki/importing/apkg.py:51: in run
    Anki2Importer.run(self, importing_v2=suffix == ".anki21")
pylib/anki/importing/anki2.py:49: in run
    self._prepareFiles()
pylib/anki/importing/anki2.py:62: in _prepareFiles
    self.src = Collection(self.file)
pylib/anki/collection.py:151: in __init__
    self.reopen()
pylib/anki/collection.py:292: in reopen
    self._backend.open_collection(
out/pylib/anki/_backend_generated.py:144: in open_collection
    raw_bytes = self._run_command(3, 0, message.SerializeToString())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <anki._backend.RustBackend object at 0x10698b220>, service = 3
method = 0
input = b'\nI/var/folders/20/_t6_h0cx4nl1qr58y1km9l740000gn/T/anki_temp/l54w6k5b.anki2\x12I/var/folders/20/_t6_h0cx4nl1qr58y1km9l740000gn/T/anki_temp/l54w6k5b.media\x1aM/var/folders/20/_t6_h0cx4nl1qr58y1km9l740000gn/T/anki_temp/l54w6k5b.media.db2'

    def _run_command(self, service: int, method: int, input: bytes) -> bytes:
        start = time.time()
        try:
            return self._backend.command(service, method, input)
        except Exception as error:
            error_bytes = bytes(error.args[0])
        finally:
            elapsed = time.time() - start
            if current_thread() is main_thread() and elapsed > 0.2:
                print(f"blocked main thread for {int(elapsed*1000)}ms:")
                print("".join(traceback.format_stack()))
    
        err = backend_pb2.BackendError()
        err.ParseFromString(error_bytes)
>       raise backend_exception_to_pylib(err)
E       anki.errors.BackendError: JsonError { info: "decoding deck config: missing field `easyDaysPercentages`" }
```

**Comment by Expertium** [comment]
@dae Jarrett marked it as "Ready for review"

**Comment by dae** [comment]
Thanks, I'll do my best to get to this tomorrow.

**Comment by dae** [comment]
Heads up for future PRs: we should avoid expect() when processing user input

I haven't looked too carefully at the actual balancing logic as I presume you've tested that, but no major issues stood out to me. Looks good as a whole :+1: Thanks Jarrett.

We'll want to add a tooltip/manual entry in the future, perhaps near release time.

**Pull request merged**
