### PR TITLE
strip to test whether field is empty

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
There are two reason for this PR.
The first one is that a field with only spaces and new line should probably be considered as empty anyway.
The second is that my last PR created a bug. The field value contained far more spaces than it should have. I didn't realize that because of this, even if those spaces were not taken into account in the GUI, there were taken into account to decide that the field is not empty
https://github.com/ankitects/anki/pull/524

Of course, I could also correct the change done in the javascript file. But in this case, I believe that this correction is more appropriate

### CODE REVIEW

**Comment by dae** [comment]
I think the HTML changes are causing problems in other areas like the HTML editor (ctrl+shift+x) as well, and there may be other areas as well - I think it's probably safest to remove the whitespace from the .ts file as well.

**Comment by dae** [comment]
(not all of it, just inside the field div)

**Comment by Arthur-Milchior** [comment]
One more commit pushed, to crerect it

**Comment by dae** [comment]
Thanks!

**Pull request merged**
