### PR TITLE
Template filter all field

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
I love the add-on which allow to edit fields directly in reviewer.
I'd appreciate to let it be applied to each field. Without having to manually enter a filter name in each field. This this hook

### CODE REVIEW

**Comment by dae** [comment]
That won't work - only fields with custom filters are passed back to Python, so that hook would only receive the ones that already have custom filters on them.

**Comment by Arthur-Milchior** [comment]
Oh okay. I didn't realize that the back end just returned a single string if all fields are known.
Is there any easy way to have this kind of effect with a hook ? I still would find it quite practical. However, I don't know rust at all right now, so I won't try to change it immediately

**Comment by dae** [comment]
I'm afraid not

**Comment by Arthur-Milchior** [comment]
Would you accept to reopen this PR ? 
I just pushed a new commit, which ensure that if the hook template_filter_all_field is non-empty, then each fields are returned separately. This allow the hook to works and does not slow anki unless an add-on uses such a hook.
I assume that at some point, you may want to use rust to quickly check whether a card is "empty" or not instead of relying on 'req'. If it is ever the case, more change will need to occur in `render_card_from_context` in order to ensure that no `return_all_fields` remains true (and probably that no filter is applied, in order to win some time, and that only question is computed...)
But I'll leave this to later commits if and when it's necessary

**Pull request closed without merging**
