### PR TITLE
Use `Card %d` for IO template names

### LINKED ISSUE #3043: Image Occlusion `Cards...` preview uses `Cloze %d` as the cards names
As an example, that leads to a problem in portuguese, since the current translation for cloze is literally `Words omission`

image

### PR DESCRIPTION
**Pull request by BrayanDSO**
* Fixes #3043

image

image

### CODE REVIEW

**Comment by dae** [comment]
My thinking in #3043 is that we'd use 'card x' for both I/O notetypes and normal clozes, so we don't need to check what type of card it is.

You should be able to fix the formatting issues with './ninja format'

**Comment by BrayanDSO** [comment]
AFAIU, that box in the right of `Options` is only shown in `Cloze` types

'./ninja format'. I tried but it didn't work nor I got any error messages, and I ran out of time. I'll try to debug it later

**Comment by dae** [comment]
I/O notetypes are cloze notetypes. Your code is showing something different for each of them; I'm suggesting we just use the same string in both cases.

**Comment by dae** [comment]
You can use `./ninja check -v` to see the commands that are run, and can run them manually if you want to see what they output.

**Comment by dae** [comment]
No worries - thank you!

**Comment by abdnh** [comment]
> Actually, I was just using Powershell instead of Bash. Fixed it now

You can still use PowerShell if you have Bash on your path by the way.

**Pull request merged**
