### PR TITLE
Add memorized option to FSRS simulation graph

### PR DESCRIPTION
**Pull request by Luc-Mcgrady**
~~Depends on https://github.com/open-spaced-repetition/fsrs-rs/pull/261#issue-2751861307.~~

image

Forum: https://forums.ankiweb.net/t/feature-request-estimated-total-knowledge-over-time/53036

Also now hides hidden values in the tooltip: https://forums.ankiweb.net/t/suggestion-dont-show-data-for-hidden-line-on-tooltip/53444

### CODE REVIEW

**Comment by brishtibheja** [comment]
I think "memorised" is bit of a done and dusted matter, what do you think of calling it, "remembered" or maybe "knowledge" which I know is vague, but that's the term "Estimated total knowledge" is using.

**Comment by L-M-Sherlock** [comment]
The v1.4.6 is published: https://crates.io/crates/fsrs/

**Comment by L-M-Sherlock** [comment]
The v1.4.7 is published: https://crates.io/crates/fsrs/

**Comment by dae** [comment]
Nothing to note. Thanks Luc!

**Pull request merged**
