### PR TITLE
Makes strings in the Compute Optimal Retention section translatable

### PR DESCRIPTION
**Pull request by tekinosman**

### CODE REVIEW

**Comment by dae** [comment]
These were left untranslated, because the feature is listed as experimental, and may change. @L-M-Sherlock, do you think we should be translating these strings yet?

**Comment by L-M-Sherlock** [comment]
It's still experimental. And I plan to refactor it in the feature. Some strings will change.

**Comment by tekinosman** [comment]
My apologies for this oversight. Let's close it.

**Comment by dae** [comment]
No problem, thank you for contributing in any case!

**Pull request closed without merging**
