### PR TITLE
add dockerfile

### PR DESCRIPTION
**Pull request by LuckyTurtleDev**
This pr add a dockerfile for the sync service. So it can easy self hosted.

It can be build by executing `docker build --build-arg version=23.10 . `.

I would recommend to build an publish it automatic on ghcr.io at release, by using the ci. Sadly I have no appearance with buildkite.

### CODE REVIEW

**Comment by dae** [comment]
Sorry, I don't have the bandwidth to deal with ghcr at this time. If you'd like this included, please make some changes:

- move docs/docker/* into docs/docker/anki
- move your file into docs/docker/syncserver
- add yourself as a maintainer so people reach out to you if it breaks
- add a small readme in that folder telling people how to use it
- ensure CI checks pass

**Comment by LuckyTurtleDev** [comment]
Sadly I can only maintain ghcr with github actions. For buildkit I have on test system and no experience.

**Comment by LuckyTurtleDev** [comment]
For now I had setup an mirror of this repo [LuckyTurtleDev/anki-server-docker](https://github.com/LuckyTurtleDev/anki-server-docker/blob/main/.github/workflows/docker.yml) and build an and publish the image there for every new tag matching `[0-9]+.[0-9]+`.
see https://github.com/LuckyTurtleDev/anki-server-docker/blob/main/.github/workflows/docker.yml

**Comment by dae** [comment]
I'm not suggesting you publish images via CI, I'm just asking you to ensure the existing CI tests pass (i.e. you add yourself to the contributors file), and that you provide contact details in the dockerfile/readme so that if people encounter problems with it, they contact you instead of me.

**Comment by Tooa** [comment]
I stumbled upon this MR while searching for a containerized anki-sync-server for my Raspberry Pi. Find attached a slighly modified variant for cross-compiling the sync-server:

https://gist.github.com/Tooa/ca788bdb885ae2dcc5f2b0bebd6e57ed

Creating a Docker image for arch64 is as simple as replacing the Docker image tag and cross compile target according to the [rust cross documentation](https://github.com/rust-cross/rust-musl-cross).

Maybe someone will find this useful. Hope you guys don't mind hijacking this MR. Have a nice evening!

**Comment by LuckyTurtleDev** [comment]
> Creating a Docker image for arm64 is as simple as replacing the Docker image tag 

No idea how this should work. You must use some kind of if function to select the right docker version.
```bash
From --platform=$BUILDPLATFORM ghcr.io/rust-cross/rust-musl-cross:$(
if   [ "$TARGETPLATFORM" == "linux/amd64"  ]; then echo "x86_64-unknown-linux-musl" \
    elif [ "$TARGETPLATFORM" == "linux/arm64"  ]; then echo "aarch64-unknown-linux-musl" \
    elif [ "$TARGETPLATFORM" == "linux/arm/v7" ]; then echo "armv7-unknown-linux-musleabihf" \
    else echo "Unknown architecture $TARGETPLATFORM"; exit 1; \
    fi )
```

**Comment by LuckyTurtleDev** [comment]
> I'm not suggesting you publish images via CI,

I think a dockerfile at some place folder in the git would not be very helpful. As long it is not build and publish to some  docker registry.

**Comment by dae** [comment]
Fair enough. I'm afraid I am not interested in integrating Docker publishing into the CI pipeline at this time, so if you don't wish to add this to the docs, there is nothing more to do on this end.

**Comment by LuckyTurtleDev** [comment]
I have create an image with auto update and build/publish now: https://github.com/LuckyTurtleDev/docker-images/tree/main/dockerfiles/anki

The readme is currently missing. But will be add later.

**Comment by LuckyTurtleDev** [comment]
I finally add an readme: https://github.com/LuckyTurtleDev/docker-images/tree/main/dockerfiles/anki

**Comment by LuckyTurtleDev** [comment]
@Tooa I have add multiplatform build. It is currently available under https://github.com/LuckyTurtleDev/docker-images/pkgs/container/test-anki for testing. If it works I will merge the changes to main.

**Pull request closed without merging**
