### PR TITLE
Fix missing pyaudio blocking Anki from running

### PR DESCRIPTION
**Pull request by evandrocoan**
Continuing from https://github.com/ankitects/anki/pull/606 - Remove pyaudio as mandatory dependency

### CODE REVIEW

**Comment by dae** [comment]
Normal users don't see anything printed to stdout, so this warning will likely be missed. It would be better to use showWarning() when the user actually tries to record something, telling them they need to install pyaudio. Instructing them to use python/pip is also not a great idea, as that may not be appropriate for users running using a system-installed Python

**Comment by evandrocoan** [comment]
I used show warning and suggested to install pyaudio. This warning should only be seen by someone who installed the wheel from pypi or from the source as the packed version of Anki should have pyaudio embed.

**Comment by dae** [comment]
Thanks!

**Comment by dae** [comment]
Re your previous comment, some Linux distributions package up Anki themselves and don't always list the dependencies as required, so this warning will be seen more frequently than you might expect :-(

**Pull request merged**
