### PR TITLE
correct missing french translation

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
I took a loot at missing French translations. Translated what I thought was really missing, corrected the remaining in the code

### CODE REVIEW

**Comment by dae** [comment]
Could you check the formatting? I recommend you add a pre-push hook in git to automatically catch such problems before pushing, as described in README.contributing. It's helped me multiple times in the past :-)

**Comment by dae** [comment]
(if the long comments need to be wrapped, I think you can use multiple #T: lines)

**Comment by Arthur-Milchior** [comment]
Oh. I didn't know that multiple lines were acceptable. That's actually why I didn't do anything about this particular case.

**Comment by dae** [comment]
You can check it works correctly by running qt/i18n/update-pot - it should add the split lines to anki.pot

**Comment by Arthur-Milchior** [comment]
It indeed works.
Related question: is there a way to let random user have easy read-only access to crowdin's translation ?
For the sake fo consistency, ankidroid asks its translator to check anki's translation and use the same when possible. That was easy with previous translation method. But now, it means our translator need either to ask your permission to have access to translation, how to figure out how to read translation from anki source file. I fear that it's long and complex for translators. If we can just have a link to give them, that would be so much easier

**Comment by dae** [comment]
I gave it a try, but it doesn't look like it's possible to provide read only access - the site asks users to sign up when they try to view a language. The translation files are on GitHub however, so you can  point users to https://github.com/ankitects/anki/tree/master/qt/i18n/translations/anki.pot and they can click on the language of interest, then use ctrl+f/cmd+f to search in the page for the string they're looking for.

**Comment by dae** [comment]
(did you run black? check is still failing)

**Comment by dae** [comment]
Thanks!

**Comment by dae** [comment]
The new translation site allows people to view the translations without signing up: https://anki.tenderapp.com/discussions/announcements/138-more-updates-to-ankis-translations

**Comment by Arthur-Milchior** [comment]
Thanks; I ported the information to ankidroid's wiki

**Pull request merged**
