### PR TITLE
Search_model has context

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
have an add-on which allow to open multiple windows. So would like to know which browser has done the search. This
would allow me to have browser with various setting. In particular, I've an add-on which allow to show a single line by
note, and I would like for some browser to have this feature on and for some other to have this feature off.

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Related to "a single line by note in the browser", I would love for such a query to be created directly in rust if you can. 
Before moving to rust, I think I was making the query directly, which allowed it to be quick. With rust, today, I get a list of card id, and I need to make a lot of query to get the note id and then be able to find out which cards to keep and which cards to remove. That made this add-on quite slow. (Almost half a minute for my whole collection)

**Comment by dae** [comment]
There is search_notes(), but it wasn't intended for use in the browse screen, and does not support ordering. Your best bet is probably to query all the nids in one go using id2str

**Comment by dae** [comment]
Re the PR, how about using the browser instance instead? The data model can be retrieved from it, and it seems to make more sense to pass the top levels object.

**Comment by Arthur-Milchior** [comment]
My thought was that the Context is created in the Model and I expect it to change only informations regarding the model and not the remaining of the browser. Anyway, there is one browser by model and one model by browser, so anything is fine

**Comment by dae** [comment]
Either option could work, since they both link to each other - I was just thinking of how other browser hooks tend to pass in the browser, so this would be a bit more consistent. Not a big issue in any case :-)

**Pull request merged**
