### PR TITLE
Reimplement "Show Duplicates" button in editor

### PR DESCRIPTION
**Pull request by kleinerpirat**
https://forums.ankiweb.net/t/anki-2-1-50-beta/15608/66

image

I figured the `LabelContainer` is the better spot for this element, considering it turns red when there are dupes.

### CODE REVIEW

**Comment by hgiesel** [comment]
I like the positioning.

I tried to avoid putting any logic other than "Edit the content of a single field" into `EditorField`. [Here](https://github.com/kleinerpirat/anki/compare/editor-show-dupes...hgiesel:editor-show-dupes)'s a suggestion how we can also avoid this for dupes. Basically I just put it next to the badges :)

**Comment by kleinerpirat** [comment]
Thanks for looking over this! I'm gladly incorporating your approach into this PR.
Personally, I prefer the link to be centered though:

image
image

Would you rather keep it within field-state or got a technical argument that speaks against https://github.com/ankitects/anki/pull/1550/commits/3a4511042da7083a52d67b58550b13d873dcbea5 ?

**Comment by hgiesel** [comment]
I'd rather keep it within field-state (for the same reason I mentioned above). You can achieve the same with some styling on `FieldState`:

```css
flex-grow: 1;
justify-content: flex-end;
```

(And remove the `justify-content-between` class)

And then on the `DuplicateLink`, you set:

```css
text-align: center;
flex-grow: 1;
```

One advantage I'm thinking of: It allows us a bit more freedom, when adapting the editor styling for mobile.

**Comment by kleinerpirat** [comment]
Nice one, didn't think of that! (also had some trouble understanding your argument before :sweat_smile:).

**Comment by dae** [comment]
Looks great, thank you both!

**Pull request merged**
