### PR TITLE
[Qt 6.7] Set ForceDarkMode attribute in AnkiWebView

### PR DESCRIPTION
**Pull request by louwers**
This PR allows using [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) in styles. For example:

```css
p {
 color: red;
}

@media (prefers-color-scheme: dark) {
  p {
   color: blue;
  }
}
```

I know the `night-mode` is already added to the HTML root, but since there is now a CSS feature for this I think it is preferred. Also, it will work with external CSS style sheets that are dark mode aware.

Note that this depends on #3342 since `QWebEngineSettings.ForceDarkMode` was [introduced in Qt 6.7](https://doc.qt.io/qtforpython-6/PySide6/QtWebEngineCore/QWebEngineSettings.html#PySide6.QtWebEngineCore.QWebEngineSettings.WebAttribute
), hence this is marked a Draft for now.

https://github.com/user-attachments/assets/137dbf24-2002-48df-91a8-99313cdcd04c

### CODE REVIEW

**Comment by dae** [comment]
It might be worth adding a version check and doing this conditionally - even if we stop providing Qt5 builds, there may be Linux distros who continue to ship Anki with a Qt5 or earlier Qt6 version.

**Comment by louwers** [comment]
Good idea, will add the version check.

**Comment by louwers** [comment]
Moved to `on_theme_did_change` and setting the setting on the page so that it updates dynamically.

Added `hasattr` check so this will start working for Qt 6.7 builds.

**Comment by dae** [comment]
Thanks Bart - appreciated!

**Pull request merged**
