### PR TITLE
Replace hardcoded magic number with file-scoped constant.

### PR DESCRIPTION
**Pull request by devingdaniels**
Refactored the flag handling logic in the Cards.py file to replace the hardcoded magic number 0b111 with a named constant, USER_FLAG_MASK. This change aligns with Anki's goal of improving code readability and maintainability.

### CODE REVIEW

**Comment by dae** [comment]
Hi Devin,

You have some unrelated changes there, which are breaking the checks. If you remove the irrelevant changes and ensure the tests pass, I can merge this in. But please avoid refactoring PRs in the future. I've updated the out-of-date contributing guidelines to make this clearer: https://github.com/ankitects/anki/blob/main/docs/contributing.md#refactoring

**Comment by devingdaniels** [comment]
> Hi Devin,
> 
> You have some unrelated changes there, which are breaking the checks. If you remove the irrelevant changes and ensure the tests pass, I can merge this in. But please avoid refactoring PRs in the future. I've updated the out-of-date contributing guidelines to make this clearer: https://github.com/ankitects/anki/blob/main/docs/contributing.md#refactoring

Thanks for the feedback. I removed the auto-save formatting from the first commit and added my name to the contributors list.

**Comment by dae** [comment]
Thanks Devin! There are still some problems I'm afraid. You changed the trailing newline, which broke the formatting check:

https://buildkite.com/ankitects/anki-ci/builds/8296#01913d38-2ac2-4e97-83fd-ce6cf0ae0713

Also, someone else changed the CONTRIBUTORS file, which has caused a conflict. Please rebase your changes and force-push them, which should allow me to merge this cleanly.

**Comment by dae** [comment]
Please re-open when you're ready.

**Pull request closed without merging**
