### PR TITLE
Fix a11y issues with Badge component

### PR DESCRIPTION
**Pull request by adeleke5140**
This PR will fix the a11y issues with the badge component by replacing the `span` with a semantically accurate `button` component.

### CODE REVIEW

**Comment by dae** [comment]
Thank you! This may need a bit of a tweak to get the margins/padding like they were before:
2023-10-11T15:33:22,573123082+10:00
2023-10-11T15:32:58,398082976+10:00

**Comment by adeleke5140** [comment]
I missed that. I would fix asap.

**Comment by adeleke5140** [comment]
I had to use a ruler to properly measure it lol but it should be all good now.

**Comment by dae** [comment]
Thank you!

**Comment by abdnh** [comment]
This has affected tab navigation - the badges are now focusable.

**Pull request merged**
