### PR TITLE
fix outdated help site

### PR DESCRIPTION
**Pull request by johan456789**

### CODE REVIEW

**Comment by dae** [comment]
Changing this will require more work I'm afraid: https://github.com/ankitects/anki/pull/609

**Comment by johan456789** [comment]
I added commits for all url path changes called using `openHelp`.

Could you help me with the checks? All my edits are url change except [this one](https://github.com/ankitects/anki/pull/782/files#diff-4ee94d44a739ced4d298e304db8a986d). I don't understand why there are problems.

**Comment by dae** [comment]
Thanks for putting in the time to do that! The failures can be fixed with 'make fix' - some long lines just need wrapping.  If you could do that in the future that would be great; this time I'll just merge it as is and commit a follow-up fix.

**Comment by johan456789** [comment]
> The failures can be fixed with 'make fix' - some long lines just need wrapping. If you could do that in the future that would be great;

Ah got it! I will remember next time.

If possible, could you add tag `hacktoberfest-accepted` to this pull request? I want to participate in [Hacktoberfest](https://hacktoberfest.digitalocean.com/). Thank you!

**Comment by dae** [comment]
It's nice that DigitalOcean are trying to reduce the negative impact HacktoberFest can have, but it'd be nicer if they come up with a way that doesn't require polluting the repo with a new label. :-) Yours was a useful contribution in any case, thank you.

Please let me know when they've approved your contribution, so I can clean up the label.

**Comment by johan456789** [comment]
Sorry for the inconvenience. I think they should just count merged PRs and use invalid or spam tags for reducing noise. 

Thanks for the tag. I'm not actually doing it for Hacktoberfest, it's just that I found something broken and then I tried to fix it. A T-shirt is just a nice touch ;) Sad that spammers don't get the spirit of open source. 

> Please let me know when they've approved your contribution, so I can clean up the label.

Sure, I will let you know.

**Comment by johan456789** [comment]
@dae Thanks for your help. You can delete the tag now.

**Comment by dae** [comment]
Thanks for letting me know :-)

**Pull request merged**
