### PR TITLE
Improve hover feedback on various widgets

### PR DESCRIPTION
**Pull request by kleinerpirat**
image

This makes the use of `cursor: pointer` (or `Qt.CursorShape.PointingHandCursor`) more consistent across the application, resulting in more clickable looking widgets and labels.

### CODE REVIEW

**Comment by kleinerpirat** [comment]
Not sure if the test error is on me or if mypy just doesn't understand the shims.

**Comment by dae** [comment]
You can use the separate without_qt5_compat_wrapper() function to fix the type check. Happy to merge once the tests pass :-)

**Comment by kleinerpirat** [comment]
```
OSError: [Errno 28] No space left on device: '/state/bazel/anki/sandbox/processwrapper-sandbox/975/execroot/ankidesktop/bazel-out/k8-fastbuild/bin/qt/pytest.runfiles/ankidesktop/qt/tests/__pycache__'
```
Have I caused a memory leak somehow? :see_no_evil:

**Comment by dae** [comment]
I don't have cache pruning set up on the CI box, so I need to manually prune it when it fills up :-)

**Comment by dae** [comment]
Tests are green now - thanks!

**Pull request merged**
