### PR TITLE
 Turn on check_untyped_defs for aqt.taglimit, aqt.update and aqt.browser

### PR DESCRIPTION
**Pull request by mkrump**
For ankitects/help-wanted#4

Saw the following errors after turning on check_untyped_defs for aqt.taglimit, aqt.update and aqt.browser. 

7356756
```
aqt/taglimit.py:13: error: Cannot assign to a method  [assignment]
            self.parent = parent
            ^
aqt/taglimit.py:14: error: "Callable[[], QObject]" has no attribute "deck"  [attr-defined]
            self.deck = self.parent.deck
                        ^
aqt/taglimit.py:66: error: Incompatible types in assignment (expression has type "str", variable has type "List[Any]")  [assignment]
            self.tags = ""
                        ^
aqt/taglimit.py:92: error: Incompatible types in assignment (expression has type "str", variable has type "List[Any]")  [assignment]
            self.tags = ""
                        ^
```
b2cbe10
```
aqt/update.py:50: error: "pyqtSignal" has no attribute "emit"  [attr-defined]
                self.newMsg.emit(resp)
                ^
aqt/update.py:52: error: "pyqtSignal" has no attribute "emit"  [attr-defined]
                self.newVerAvail.emit(resp["ver"])
                ^
aqt/update.py:55: error: "pyqtSignal" has no attribute "emit"  [attr-defined]
                self.clockIsOff.emit(diff)
                ^
aqt/update.py:61: error: Argument 1 to "setStandardButtons" of "QMessageBox" has incompatible type "int"; expected
"Union[StandardButtons, StandardButton]"  [arg-type]
        msg.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
```
b5222f9
```
aqt/browser.py:106: error: "Callable[[Iterable[QPersistentModelIndex], LayoutChangeHint], None]" has no attribute "emit"  [attr-defined]
                self.layoutChanged.emit()
                ^
aqt/browser.py:133: error: Argument 1 to "setFamily" of "QFont" has incompatible type "Union[str, int]"; expected "str"  [arg-type]
                f.setFamily(t.get("bfont", "arial"))
                            ^
aqt/browser.py:134: error: Argument 1 to "setPixelSize" of "QFont" has incompatible type "Union[str, int]"; expected "int"  [arg-type]
                f.setPixelSize(t.get("bsize", 12))
                               ^
aqt/browser.py:148: error: Incompatible types in assignment (expression has type "int", variable has type "AlignmentFlag")  [assignment]
                    align |= Qt.AlignHCenter
                    ^
aqt/browser.py:302: error: Unsupported operand types for + ("int" and "str")  [operator]
                    t += " %d" % (c.ord + 1)
                         ^
aqt/browser.py:302: note: Left operand is of type "Union[str, int, None]"
aqt/browser.py:311: error: Unsupported operand types for + ("str" and "int")  [operator]
                    t = "(" + t + ")"
                        ^
aqt/browser.py:311: note: Right operand is of type "Union[str, int, None]"
aqt/browser.py:1513: error: Incompatible types in assignment (expression has type "Previewer", variable has type "None")  [assignment]
                self._previewer = PreviewDialog(self, self.mw, self._on_preview_closed)
                                  ^
aqt/browser.py:1514: error: "None" has no attribute "open"  [attr-defined]
                self._previewer.open()
                ^
aqt/browser.py:2020: error: Argument 1 to "bulkAdd" of "TagManager" has incompatible type "Set[Any]"; expected "List[int]"  [arg-type]
            self.col.tags.bulkAdd(nids, _("duplicate"))
                                  ^
aqt/browser.py:2050: error: Incompatible types in assignment (expression has type "Optional[int]", variable has type "None")  [assignment]
            self.focusTo = self.editor.currentField
                           ^
aqt/browser.py:2057: error: Incompatible types in assignment (expression has type "Optional[int]", variable has type "None")  [assignment]
            self.focusTo = self.editor.currentField
                           ^
aqt/browser.py:2228: error: Need type annotation for 'map' (hint: "map: Dict[<type>, <type>] = ...")  [var-annotated]
            map = {}
```

### CODE REVIEW

**Comment by mkrump** [comment]
Wasn't sure what to do about failing

```
aqt/browser.py:2020: error: Argument 1 to "bulkAdd" of "TagManager" has incompatible type "Set[Any]"; expected "List[int]"  [arg-type]
            self.col.tags.bulkAdd(nids, _("duplicate"))
                                  ^
```

Looked like caller could probably have `Sequence[int]` signature, but didn't want to change unrelated file. Just add an ignore?

**Comment by dae** [comment]
Thanks for all your work on this Matt! It looks like changing it to Sequence would be best - the underlying backend command is already typed with Sequence, so it's just the function in tags.py that was typed wrongly. If you discover issues in other files going forward, please take the same approach - probably better to fix them when they're found than paper over them and cause issues down the line.

**Comment by mkrump** [comment]
> Thanks for all your work on this Matt! 

Thanks for making Anki! I use it every single day!

Sorry, I was wrong in my comment above. Was confused re: a `set` being an `Iterable`, but not a `Sequence`. Is it ok to just cast the set to the list after the loop (i.e. 4239c2df)? I wasn't sure if using a set there instead for a list in order to deduplicate items (or something else), but since all other functions seem to act on lists, seemed like it would be ok to cast it before passing to `bulkAdd`.

**Comment by dae** [comment]
Yeah, that should be fine - it's not a hot path. Perhaps it would have been better if the generated backend code accepted iterables (while still returning sequences), but I'm not sure if it's worth changing at this point. Thanks again!

**Pull request merged**
