### PR TITLE
fix float to int conversion DeprecationWarning

### PR DESCRIPTION
**Pull request by cecini**

### CODE REVIEW

**Comment by dae** [comment]
Where is the warning coming from?

**Comment by cecini** [comment]
Use Python with debug to run anki.
Maybe use python3 -W default also get this warning.

**Comment by dae** [comment]
Thanks, I've added this to the ./run command so we catch such errors in the future.

**Comment by cecini** [comment]
Nice that you ignore the pickle.dumps warning which need fix the pyqt.

**Pull request merged**
