### PR TITLE
Improve typing of custom fabric.Object properties

### PR DESCRIPTION
**Pull request by abdnh**

### CODE REVIEW

**Comment by dae** [comment]
Thanks as always Abdo. Under what circumstances does the current bug get triggered? Wondering whether I should rebuild 24.04.1 with this fix.

**Comment by dae** [comment]
(the typing improvements are a nice bonus, by the way :-)

**Comment by abdnh** [comment]
> Under what circumstances does the current bug get triggered?

Not really sure actually :) I recall seeing the issue while testing #3109 a couple of days ago but then I can no longer reproduce it now. I took a look now at Fabric's source to see how canvas.getObjects() is implemented: it simply copies canvas._objects, while canvas.add() appends to the array, so the issue shouldn't occur and I must have been imagining things. I'll revert this fix and keep the typing change.

**Comment by dae** [comment]
Thanks Abdo, that's welcome news - building the releases is currently rather involved, so was nice not to have to do it again for 24.04.1!

**Pull request merged**
