### PR TITLE
Redesign Qt widgets with stylesheets

### PR DESCRIPTION
**Pull request by kleinerpirat**
This PR unifies Qt widget styles across platforms.

Notable changes:
- The default border-radius of `5px` is used in almost all widgets except menus.
- All buttons use `cursor: pointer` regardless if Qt or web component.
- Scrollbars look the same everywhere, across themes and platforms.
- The fusion vars for dark theme have been changed (respective files and objects still need to be renamed, but I'll wait for #2016 to be merged first.)
- Several color variables for buttons and scrollbars are introduced.

# Dark theme
 

# Light theme

### CODE REVIEW

**Comment by kleinerpirat** [comment]
Important note: I made this apply to all systems for now so you guys can easily test it.

I got no problems leaving macOS als it is, once you've approved the changes are good for Linux and Windows.

**Comment by kleinerpirat** [comment]
As a test, I merged the two PRs in the following branch: https://github.com/kleinerpirat/anki/tree/redesign-test

image

**Comment by dae** [comment]
Currently doesn't compile

**Comment by kleinerpirat** [comment]
Oh, sorry. I messed up and merged in the wrong direction.

**Comment by dae** [comment]
Ok, I've given this a try. I'm not 100% sold on some of these changes, such as the tab widget headers, darker background in night mode, and the left/right margins on the buttons. But I am no UI expert, and I am happy to give these a try in a beta so we can get feedback from other users.

Could you exclude the changes on Macs before I merge this in?

**Comment by dae** [comment]
For some reason the background of the preferences screen is a lot brighter on a Mac - any ideas?
Screen Shot 2022-09-08 at 8 15 35 pm

**Comment by dae** [comment]
Nevermind, I've addressed it with #2054

**Pull request merged**
