### PR TITLE
Sidebar delete deck

### PR DESCRIPTION
**Pull request by BlueGreenMagick**
Add 'delete' to sidebar deck context menu.

### CODE REVIEW

**Comment by dae** [comment]
I like the feature, just a couple of points:

- can we break the code into a function that is shared between deckbrowser.py and this file, instead of copying & pasting?
- a fut.result() call is required in on_done to check for any errors that happened in the background - you can discard the result; it will raise on error

**Comment by BlueGreenMagick** [comment]
Regarding having a shared function that asks for deck rename, do you want me to put it in utils.py, or for sidebar to call it from deckbrowser.py? Or is there a better option?

**Comment by BlueGreenMagick** [comment]
Done. Is this alright?

**Comment by dae** [comment]
Looks good, thanks!

Some minor points:
- the count checking should ideally also be in the background, which means that ask_deck_delete would need to be converted to use a callback. It's not a dealbreaker, as there are still lots of other places in the code that need similar updating, and the counts check is usually not too slow.
- future.result() can be used without assigning to anything

**Pull request merged**
