### PR TITLE
add saveGeom and restoreGeom to htmlEditor

### PR DESCRIPTION
**Pull request by sandersantema**
This should solve the geometry part of: https://github.com/ankitects/help-wanted/issues/1

This doesn't edit a maximize button, partially because I have no knowledge of what that should be KDE adds a maximize button for me natively. 

I ran `make check` which failed on a few files but I assume this is okay since these are files which I haven't touched. 

I'll try to add a commit to this pull request to add myself as a contributor after this commit. Given this is the first time I contributed I'd obviously like to hear if something isn't correct about the pull request (apart from the code itself). I wouldn't know exactly if the code is correct given I'm inexperienced with python, but it works, if anything is wrong it would be great to get some pointers so I can read up about it. At least it's a nice little pr to start out with :)

I've commited something else too: https://github.com/sandersantema/anki/commit/cf390176ed7f542d0d21c7eca79536987db02f49

This I wasn't able to test and I'm not sure it's correct but this is how it's done in the docs: https://docs.python.org/3/library/warnings.html#overriding-the-default-filter

### CODE REVIEW

**Comment by evandrocoan** [comment]
@sandersantema, can you run `make fix` and commit the formatting fixes? https://github.com/ankitects/anki/pull/638/checks?check_run_id=709252895#step:25:983

**Comment by evandrocoan** [comment]
It seems a bug on Anki. I just did a new build from the actual master the still the same: https://github.com/evandroforks/anki/runs/710302038?check_suite_focus=true

**Comment by dae** [comment]
@sandersantema thanks for contributing! w looks safe to remove . Would you mind running 'make fix' to fix the formatting, and rebasing your changes on the latest master to fix the merge issue? If you continue to get errors when running make check, please paste them here.

**Comment by dae** [comment]
Not sure what's happened there - it looks like you rebased to an earlier point, then pulled the recent merged changes in from master? https://github.com/ankitects/anki/pull/638/files has become a bit messy as a result. Would you mind trying again? Feel free to open a new branch from master, cherry pick the changes and submit a new PR if that's easier

**Comment by sandersantema** [comment]
> Not sure what's happened there - it looks like you rebased to an earlier point, then pulled the recent merged changes in from master? https://github.com/ankitects/anki/pull/638/files has become a bit messy as a result. Would you mind trying again? Feel free to open a new branch from master, cherry pick the changes and submit a new PR if that's easier

I made some mistakes rebasing indeed, it still seems a little messy although I tried to combine some of the commits regarding mistakes together. Is it better at this point or shall I open a new PR?

**Pull request closed without merging**
