### PR TITLE
Add a hook to execute after pasting in a field

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
I expect to use it to ensure that images are resizable after they get pasted in a field

### CODE REVIEW

**Comment by dae** [comment]
editor_did_paste would better match the existing hook names. Can't guarantee this code path will stick around for a long time, as the paste handling might get refactored in future editor changes, but happy to add the hook for now.

**Comment by dae** [comment]
(to clarify, please fix the name first :-)

**Comment by Arthur-Milchior** [comment]
Anyway, if you deal with resizing image directly in Anki, I may never use this hook. As I expected to use it to deal with ensuring new images are resizable. 
Name changed, because it might still be useful maybe

**Comment by dae** [comment]
Thanks Arthur!

**Pull request merged**
