### PR TITLE
Prevent MathJax editor from closing unexpectedly when selecting text

### PR DESCRIPTION
**Pull request by hikaru-y**
Addresses item 1 of #2325 (= https://github.com/ankitects/anki/issues/2325#issuecomment-1463223094).

### CODE REVIEW

**Comment by dae** [comment]
Thanks for looking into this Hikaru! That approach feels a little hacky - what do you think about using a mousedown event instead of a click event instead?

```diff
diff --git a/ts/components/WithFloating.svelte b/ts/components/WithFloating.svelte
index 50773fb83..d120eb7c1 100644
--- a/ts/components/WithFloating.svelte
+++ b/ts/components/WithFloating.svelte
@@ -17,7 +17,7 @@ License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
     import isClosingClick from "../sveltelib/closing-click";
     import isClosingKeyup from "../sveltelib/closing-keyup";
     import type { EventPredicateResult } from "../sveltelib/event-predicate";
-    import { documentClick, documentKeyup } from "../sveltelib/event-store";
+    import { documentMouseDown, documentKeyup } from "../sveltelib/event-store";
     import portal from "../sveltelib/portal";
     import type { PositioningCallback } from "../sveltelib/position/auto-update";
     import autoUpdate from "../sveltelib/position/auto-update";
@@ -134,7 +134,7 @@ License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
             return;
         }

-        const closingClick = isClosingClick(documentClick, {
+        const closingClick = isClosingClick(documentMouseDown, {
             reference,
             floating,
             inside: closeOnInsideClick,
diff --git a/ts/components/WithOverlay.svelte b/ts/components/WithOverlay.svelte
index ec5c50b9c..05f118f7e 100644
--- a/ts/components/WithOverlay.svelte
+++ b/ts/components/WithOverlay.svelte
@@ -17,7 +17,7 @@ License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
     import isClosingClick from "../sveltelib/closing-click";
     import isClosingKeyup from "../sveltelib/closing-keyup";
     import type { EventPredicateResult } from "../sveltelib/event-predicate";
-    import { documentClick, documentKeyup } from "../sveltelib/event-store";
+    import { documentMouseDown, documentKeyup } from "../sveltelib/event-store";
     import type { PositioningCallback } from "../sveltelib/position/auto-update";
     import autoUpdate from "../sveltelib/position/auto-update";
     import type { PositionAlgorithm } from "../sveltelib/position/position-algorithm";
@@ -105,7 +105,7 @@ License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
             return;
         }

-        const closingClick = isClosingClick(documentClick, {
+        const closingClick = isClosingClick(documentMouseDown, {
             reference,
             floating,
             inside: closeOnInsideClick,
diff --git a/ts/sveltelib/event-store.ts b/ts/sveltelib/event-store.ts
index 0930919f4..2b7f3ef5a 100644
--- a/ts/sveltelib/event-store.ts
+++ b/ts/sveltelib/event-store.ts
@@ -34,7 +34,7 @@ function eventStore<T extends EventTarget, K extends keyof EventTargetToMap<T>>(

 export default eventStore;

-const documentClick = eventStore(document, "click", MouseEvent);
+const documentMouseDown = eventStore(document, "mousedown", MouseEvent);
 const documentKeyup = eventStore(document, "keyup", KeyboardEvent);

-export { documentClick, documentKeyup };
+export { documentKeyup, documentMouseDown };
```

**Comment by hikaru-y** [comment]
Thanks for the suggestions! That's a much cleaner and better solution.

**Comment by dae** [comment]
Thanks Hikaru!

**Comment by dae** [comment]
Unfortunately my solution brought unintended breakages - nothing is ever easy ^_^; I've pushed an alternative fix to main.

**Pull request merged**
