### PR TITLE
Explode on bridge cmd

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
My ultimate goal here is to do the following:
* have my add-on see that a blur action was sent
* execute the blur action (i.e. save the new field value)
* do some more actions. 

Currently, I can't really do that, appart by copying the code of blur in my add-on.
By putting the code of the blur action in another method, it'll let me simply call the method from another method.

As usual, I tried to put multiple commit so that each change are easy to check.

The last commit feels better to me, it ensure that commands with and without arguments are considered the same way. But my goal would be achieved even without this last commit

### CODE REVIEW

**Comment by dae** [comment]
Happy to accept this once the merge is fixed

**Comment by dae** [comment]
Formatting is failing

**Comment by Arthur-Milchior** [comment]
Corrected

**Comment by dae** [comment]
cheers

**Pull request merged**
