### PR TITLE
hook prettify_json

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
The reason I want this hooks is for my add-on 112201952
In this add-on, to be more readable, I prettify the json.
I also change the data received so that the incorrect json becomes correct before it gets loaded

### CODE REVIEW

**Comment by dae** [comment]
How about addon_config_editor_will_display_json and _will_save_json

Also a minor English point (I'm not being critical - your English is much better than my French!) - "Allows adding / Allows changing" would be more natural than "Allow to add/change" in the docs.

**Comment by Arthur-Milchior** [comment]
Done
Fun fact, if you put "\n" in a hook comment string, develop replace it by an actual new line. Which makes a lot of sens if develop consider strings as strings and not as raw text. Except that I didn't pay attention to it and so obtained strange result

**Comment by dae** [comment]
Would you mind tweaking the docstring as mentioned above as well?

**Comment by Arthur-Milchior** [comment]
Done

**Comment by dae** [comment]
You only adjusted 1 of the 2 hooks. The gui_hooks.py looks like it's including a bunch of unrelated changes as well - please check it.

**Comment by dae** [comment]
Thanks!

**Pull request merged**
