### PR TITLE
Remove check for small IO rects

### LINKED ISSUE #3267: Bug: Anki Deletes most/all of my IO clozes when modifying occlusion positions
From the video, it looks like the grouping operation may be responsible.

Originally reported on https://forums.ankiweb.net/t/bug-anki-deletes-most-all-of-my-io-clozes-when-modifying-occlusion-positions/46524

### PR DESCRIPTION
**Pull request by abdnh**
Closes #3267

@krmanik Regarding your comment
> The issue is that on clicking on canvas it add empty width/height shapes, so to exclude it, we need to check the size, the size can be decreased also.

I actually can't reproduce this. No shapes are added if I click on the canvas. Maybe something has changed since then?

### CODE REVIEW

**Comment by krmanik** [comment]
Sorry for late reply, recently got little bit busy.

Okay, Then it is good to remove, can you search in vscode for the `object.width! < 5 || object.height! < 5` it may exist in other file also?

**Comment by dae** [comment]
I'm afraid this reintroduces the problem that those checks were presumably originally added to prevent. If you open a new I/O with this PR, and click a few times, an empty shape is created each time. If you switch to the select tool, the empty shapes can be seen. Perhaps we should either a) change the threshold instead of removing it, or b) leave things as they are for now (maybe not many users are affected? the shapes have to be pretty small)

Screenshot 2024-07-21 at 3 08 07 PM

**Comment by krmanik** [comment]
I agree
Sorry dae, I didn’t get time to test before commenting.

**Comment by dae** [comment]
Not a problem! I almost missed the issue myself, as they're not immediately obvious.

**Comment by abdnh** [comment]
> Perhaps we should either a) change the threshold instead of removing it, or b) leave things as they are for now (maybe not many users are affected? the shapes have to be pretty small)

OK. I vote for leaving things as they are. That sounds reasonable.

**Pull request closed without merging**
