### PR TITLE
Improve debug console

### PR DESCRIPTION
**Pull request by RumovZ**
This is still a bit rough around the edges, but I think the ability to easily persist scripts can already be a huge time saver.

### CODE REVIEW

**Comment by dae** [comment]
Looks like a nice improvement - thanks Rumo!

**Comment by dae** [comment]
Currently the debug console opens with focus on the top dropdown - what do you think about changing that to the text box so you can type immediately?

**Comment by dae** [comment]
Nevermind - I see it already does it on Mac, so presumably this is a Linux-specific issue. Will investigate when I have a chance.

**Comment by RumovZ** [comment]
No, it seems to be on Windows, too. Makes sense to ensure the text edit is focused by default again.

**Comment by dae** [comment]
Should be fixed in https://github.com/ankitects/anki/commit/77a45365cb64284dd4a8cd2535d6cbdc2676472c

**Pull request merged**
