### PR TITLE
Announce which file it is building

### PR DESCRIPTION
**Pull request by evandrocoan**
Without this, I cannot tell on which file the installation failed:
```
Updating translations from git...
Already up to date.
Current branch master is up to date.
Compiling *.po...
<stdin>:728: 'msgid' and 'msgstr' entries do not both end with '\n'
<stdin>:810: 'msgid' and 'msgstr' entries do not both end with '\n'
F:\Cygwin\bin\msgfmt.exe: found 2 fatal errors
make[1]: *** [Makefile:31: .build/i18n] Error 1
```

With this pull request, now I know where it failed:
```
Updating translations from git...
Already up to date.
Current branch master is up to date.
Compiling *.po...
Building 'po/desktop/af/anki.po'
...
Building 'po/desktop/hu/anki.po'
<stdin>:728: 'msgid' and 'msgstr' entries do not both end with '\n'
<stdin>:810: 'msgid' and 'msgstr' entries do not both end with '\n'
F:\Cygwin\bin\msgfmt.exe: found 2 fatal errors
See the file "po/desktop/hu/anki.po.error" to find the error line number just showed!
make[1]: *** [Makefile:31: .build/i18n] Error 1
```

### CODE REVIEW

**Comment by evandrocoan** [comment]
The build process https://github.com/ankitects/anki/pull/463/checks?check_run_id=468162554 is failing because the https://github.com/ankitects/anki-desktop-i18n/ repository was broken with the latest updates on the hu language today/yesterday. I already have a pull request fixing it here: (https://github.com/ankitects/anki-desktop-i18n/pull/3 - Fixed translations on desktop/hu/anki.po)

**Comment by dae** [comment]
I've committed a simplified version of this, and stopped problems with the po files from breaking the build. I will get notified when CI breaks so can make sure the files are correct for a release, but it's not necessary to make this a hard fail during development.

**Comment by evandrocoan** [comment]
How can I know which file file/line failed when I receive:
```
<stdin>:728: 'msgid' and 'msgstr' entries do not both end with '\n'
```
I mean, `stdin` is not a file I can open to get the line `728`.

When you face this, how to you solve it?

**Comment by dae** [comment]
The approach you had in this patch was perfectly valid, I just don't really like writing files into the repo in the error case, and hope to migrate these problem strings out of gettext into the new system soon (the errors are caused because Pontoon is stripping trailing whitespace from the translator's string on the assumption the source string won't have trailing whitespace either)

**Comment by dae** [comment]
(and yes, I'd run the command manually for now, but hopefully it's not something we'll have to worry about long term)

**Comment by evandrocoan** [comment]
I see, nice! Thanks for detailed description and for the hard work!

**Pull request closed without merging**
