### PR TITLE
Add extra button group for cloze commands

### PR DESCRIPTION
**Pull request by hgiesel**
I was thinking about adding separate buttons for incremented cloze number vs. same cloze number, as an "alt" modifier wouldn't work on mobile.

However I'm struggling with adding a media directory for custom icons under `/ts/icons`. Could you give me a pointer what I'm doing wrong? Currently I just get

> text: 'Could not resolve "../../icons/contain-plus.svg"'

### CODE REVIEW

**Comment by dae** [comment]
A filegroup() references files in their source location, but eslint expects everything to be under a single root folder in bazel-bin. By using js_library(), the files are copied into the bazel-bin folder at build time, and they are then accessible by eslint.

FWIW, AnkiMobile currently uses a long-press on the cloze button to make it repeat the number, but having a separate button for it seems reasonable too.

**Comment by hgiesel** [comment]
This is what it looks like now:

Screenshot 2022-03-31 at 00 22 43

**Comment by hgiesel** [comment]
Tell me if this is to be be merged after 2.1.50, because it actually contains a bug fix regarding the editor buttons (and thus relevant for #1733)

**Comment by dae** [comment]
Ideally we'd be just fixing the bug now, and waiting until we have a larger testing window before merging in new features, as there's always a risk something will get accidentally overlooked. I don't want to take up your time asking you to change it now, but for future PRs in the next few weeks, it would be great if we could have any bugfixes separated from feature/refactoring changes. I haven't been very clear about what I was hoping for, and a bit inconsistent with what does/doesn't get merged, so I apologize for any confusion there :-)

**Pull request merged**
