### PR TITLE
Decide if element is bold by getComputedStyle (#2453)

### PR DESCRIPTION
**Pull request by mmjang**
Some testing:

image

### CODE REVIEW

**Comment by dae** [comment]
Sorry @mmjang , I didn't notice you'd pushed a PR for this until after I pushed the 400->700 change. My change lacks the getComputedStyle() call in your PR, but that doesn't seem to be necessary to fix the problem. Can you think of an example where it would be required, or do you think we are ok now?

**Comment by mmjang** [comment]
@dae `getComputedStyle` is more accurate. If the boldness style of an element is inherited from it's parent, then `element.style.fontWeight` may not work. Check this example:

image

**Comment by dae** [comment]
Thanks, that's a good point. If we fix this for BoldButton.svelte, perhaps we should be applying similar changes for underline, italics, color, and so on?

**Comment by mmjang** [comment]
> Thanks, that's a good point. If we fix this for BoldButton.svelte, perhaps we should be applying similar changes for underline, italics, color, and so on?

Yep, I think so.

**Comment by dae** [comment]
Haven't forgotten about this, just haven't had time to circle back to it yet I'm afraid.

**Comment by dae** [comment]
I've finally found time to add the italics case as well, but have left colors for now. Sorry this got blocked for so long.

**Comment by dae** [comment]
Unfortunately I had to revert this, as it caused a regression: https://forums.ankiweb.net/t/anki-24-10-beta/49989/150

**Pull request merged**
