### PR TITLE
Switch to event.key for keyboard sequences

### PR DESCRIPTION
**Pull request by hgiesel**
This adresses #1162 by moving to `event.key` instead of `event.code`. I still think there might be use cases for `event.code`, as I mentioned in the issue, for when we port the reviewert shortcuts.

This also removes the keyboard sequence timeout, and disables a started keyboard sequence if you press a "general key" (characterized by `event.location === 0`).

### CODE REVIEW

**Comment by hgiesel** [comment]
There is one more complication:
Let's take the subscript shortcut, which is `Control+=`. On an US standard keyboard, you gotta press `Control+Equals`, whereas e.g. on a German keyboard you have to press `Control+Shift+0`.
Currently Anki will reject this, as we've programmed it only take `Control` as a modifier, and all others have to be not-pressed for the shortcut to fire.

Not quite sure how to solve this.
As we'll never know which `event.key` values are hidden behind modifiers, this basically means we can only use shortcuts in the form of `Control+X`, because both Shift and Alt can change the output of `event.key`. Another approach would be to use optional modifiers more generously to cover most cases...

**Comment by dae** [comment]
Thanks for working on this. I'm not sure what the best path forward here is either, and Qt had some issues with certain keystrokes as well. If there aren't many shortcuts that are affected by this, maybe we should consider changing them to something more compatible? I thought about making some keystrokes translatable, but we can't be sure the user's keyboard will match their interface language, and presumably that would be a pain with keystrokes listed as an array.

Will event.location === 0 work with a numeric keyboard, which appears to specify a different location?

**Comment by hgiesel** [comment]
Another complication: Control+Shift+Equals and Control+Equals will both produce `=` as event.key. This means, we can no longer distinguish between `=` and `+` even on US ANSI keyboards.

I had a look into Summernote and TinyMCE, and investigated how they deal with shortcuts. Both use `event.key` for shortcuts which involve letters, and use `event.code` for shortcuts with the digit keys `Digit{0-1}`. Summernote also uses `event.code` for symbols (Remove formatting is `Ctrl+\`, where `\`, will always be the `Backslash` key), whereas TinyMCE completely avoids keys beyond the digit keys, and event.key with letters. Also, both avoid using the Alt/Option modifier with letters.

This new version uses `event.key` for shortcuts based on letters, and `event.code` for the Superscript and Subscript shortcuts, Enter, and Tab. I also left in the Cloze shortcut, as it still works, although we need to keep an eye once the underlying Chromium is updated, and then might have to change the shortcut.

**Comment by dae** [comment]
Qt 6.2 is planned for the end of Sep, so a new Chromium is hopefully not too far off.

Another issue I noticed is that the latest Chrome and Safari use the lowercase version in 'key' when shift is held down, but Qt uses the uppercase version, so I'm guessing we'll need to lowercase or uppercase the codes before comparison. What a mess ^_^;

I feel a bit uneasy about this current approach, but our options seem to be limited here. :-( Maybe one alternative would be to revert to the keycode approach and have some translation layer to map physical keys to their virtual equivalents. It would require the user to specify the layout they're using in the preferences though, and we'd need to include maps for the layouts in our code.

Are you using a qwertz keyboard? If so, when we were using the original keycode approach, was that working fine on your keyboard? I'm wondering whether it's just dvorak/colemak we need to worry about, or whether there are a bunch of other languages we'd need to provide translations for as well.

**Comment by hgiesel** [comment]
> Qt 6.2 is planned for the end of Sep, so a new Chromium is hopefully not too far off.

But AFAIK web engine is still not ported?

> Maybe one alternative would be to revert to the keycode approach and have some translation layer to map physical keys to their virtual equivalents. It would require the user to specify the layout they're using in the preferences though, and we'd need to include maps for the layouts in our code.

From my experience, people who use multiple keyboard layouts typically switch between keyboard layouts, whenever they switch the language. For example, they will switch to a German layout to type German, and switch back to English to type English. Having to set this in the preferences

**Comment by hgiesel** [comment]
The only small issue remaining is with symbol keys, which you can see with the example of subscript and superscript again. The shortcut will show `Ctrl+=`, which on a German keyboard e.g. would be `Ctrl+´`, however the shortcut still works correctly. On a Dvorak layout it is actually mapped correctly to `BracketRight` key, because it's a perfect match for it.

However I think that's as close as we can get to the perfect solution.

**Comment by dae** [comment]
Thanks Henrik, let's give this a go.

**Pull request merged**
