### PR TITLE
Template order

### PR DESCRIPTION
**Pull request by RumovZ**
https://github.com/ankitects/anki/commit/d55f0807330805bfb036c6014b7135e4d7fdd072#r70149815

I didn't change the string _names_ containing 'template'. Was that correct?
Also, I feel like we should emphasise that this about the _number_ of card types. Not sure if I expressed this well.

### CODE REVIEW

**Comment by dae** [comment]
Ordinal is not a term that comes up much in everyday speech, and it's not a term we expose to the user in the interface, so I think it might be a bit confusing. I gather you don't like 'in card type order', but the comment about showing all front->back cards first is intended to clarify that. Does moving it closer help at all, eg the following?

'in card type order (eg front->back/cloze 1 cards before back->front/cloze 2 cards)'

Otherwise looks good, and I think it's probably better not to break translations for these wording tweaks :+1:

**Comment by RumovZ** [comment]
What about number instead of ordinal? If you think that wouldn't work either, I'll just revert it to "card type order". As you said, there already is a clarifying example, and I don't feel like expanding that would improve things.

**Comment by dae** [comment]
Number works for me :-)

**Comment by dae** [comment]
Thanks Rumo!

**Pull request merged**
