### PR TITLE
add saveGeom and restoreGeom to htmlEditor and remove unused variable w

### PR DESCRIPTION
**Pull request by sandersantema**

### CODE REVIEW

**Comment by sandersantema** [comment]
I still get some errors when running `make check` but I believe that has nothing to do with my commit but rather with either missing dependencies on my side or an Anki development environment which I haven't setup properly. These are the errors:

```
anki/db.py:14:0: E0611: No name 'Cursor' in module 'sqlite3' (no-name-in-module)
anki/db.py:18:10: E1101: Module 'sqlite3.dbapi2' has no 'Error' member (no-member)
anki/db.py:23:19: E1101: Module 'sqlite3.dbapi2' has no 'connect' member (no-member)
make[1]: *** [Makefile:88: .build/lint] Error 2
make[1]: Leaving directory '/home/sandersantema/Downloads/Git/anki/pylib'
make: *** [Makefile:154: check] Error 2
```

**Comment by dae** [comment]
Thanks for the contribution!

Regarding the error, it probably means your astroid or pylint version is too old or too new - perhaps you have one of those lying around from a system package?

**Comment by sandersantema** [comment]
> Thanks for the contribution!
Thank you for your informative feedback! I hope to contribute more. 

> Regarding the error, it probably means your astroid or pylint version is too old or too new - perhaps you have one of those lying around from a system package?
I don't seem to have these installed as system packages on my openSUSE system. I can try to start anew with the anki repo later and see if the issue persists.

**Comment by evandrocoan** [comment]
@sandersantema, can you activate the `pyenv` Anki uses and run `pip list`?

These are the versions I got here on my machine (Windows 10)
```
(pyenv) F:\anki\qt\ts>pip list
Package           Version    Location
----------------- ---------- -------------
anki              2.1.28     f:\anki\pylib
appdirs           1.4.3
aqt               2.1.28     f:\anki\qt
astroid           2.3.3
atomicwrites      1.4.0
attrs             19.3.0
beautifulsoup4    4.9.0
black             19.10b0
certifi           2020.4.5.1
chardet           3.0.4
click             7.1.2
colorama          0.4.3
decorator         4.4.2
Flask             1.1.2
Flask-Cors        3.0.8
idna              2.9
isort             4.3.21
itsdangerous      1.1.0
Jinja2            2.11.2
jsonschema        3.2.0
lazy-object-proxy 1.4.3
Markdown          3.2.1
MarkupSafe        1.1.1
maturin           0.8.0
mccabe            0.6.1
mock              4.0.2
more-itertools    8.2.0
mypy              0.770
mypy-extensions   0.4.3
mypy-protobuf     1.20
packaging         20.3
pathspec          0.8.0
pip               20.1.1
pluggy            0.13.1
protobuf          3.11.3
psutil            5.7.0
py                1.8.1
PyAudio           0.2.11
pylint            2.5.0.dev1
pyparsing         2.4.7
PyQt5             5.13.2
PyQt5-sip         12.7.2
PyQtWebEngine     5.13.2
pyrsistent        0.16.0
PySocks           1.7.1
pytest            5.4.1
pywin32           227
QScintilla        2.11.4
regex             2020.4.4
requests          2.23.0
Send2Trash        1.5.0
setuptools        46.4.0
six               1.14.0
soupsieve         2.0
stringcase        1.2.0
toml              0.10.0
typed-ast         1.4.1
typing-extensions 3.7.4.2
urllib3           1.25.9
waitress          1.4.3
wcwidth           0.1.9
Werkzeug          1.0.1
wheel             0.34.2
wrapt             1.11.2
```

**Pull request merged**
