### PR TITLE
Add .venv to gitignore

### PR DESCRIPTION
**Pull request by voczi**
Not sure what the typical Anki developer uses as a dev environment. But I like to have a venv for every Python project so I can easily get code completion and such, without having to worry about local system dependency conflicts.

### CODE REVIEW

**Comment by dae** [comment]
You can put anything you want in extra/ already, or you can use out/pyenv. I don't think we should be adding new ignored files if they're not used as part of Anki's build process / not super common.

**Comment by voczi** [comment]
VS code python extension uses a default venv path set to source folder root + .venv

**Comment by dae** [comment]
Ok, that does change my opinion somewhat. But presumably there's also a way to tell VS Code to look elsewhere for a given project though - perhaps we should have the Anki repo just defaulting to out/pyenv instead?

**Comment by dae** [comment]
Happy to re-open if you'd like to continue the conversation.

**Pull request closed without merging**
