### PR TITLE
Fix field content overflowing its container

### PR DESCRIPTION
**Pull request by hikaru-y**
This fixes https://forums.ankiweb.net/t/text-can-exit-the-file/16903.

### CODE REVIEW

**Comment by hgiesel** [comment]
Seems like

```css
overflow-wrap: anywhere;
word-break: break-word;
```

also does the trick.

**Comment by hikaru-y** [comment]
Thanks, @hgiesel. I also thought of `overflow-wrap: anywhere`, but it seems that iOS doesn't support the value `anywhere`, so I used `min-width: 0`.
https://caniuse.com/mdn-css_properties_overflow-wrap_anywhere

**Comment by hgiesel** [comment]
That's why I also added `word-break: break-word`, which seems to fulfil the same purpose but is officially deprecated: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break.

**Comment by dae** [comment]
Thanks Hikaru, I appreciate you thinking about the iOS side of things as well! break-word is successfully used in AnkiMobile's current editor, so maybe that might be a better choice? It does make the intention a bit more explicit.

**Comment by hikaru-y** [comment]
> It does make the intention a bit more explicit.
I agree with you.

**Comment by dae** [comment]
Thank you both! :heart:

**Pull request merged**
