### PR TITLE
Use custom scrollbar in stats screen, use grid layout and tweak CSS

### PR DESCRIPTION
**Pull request by kleinerpirat**
https://forums.ankiweb.net/t/anki-2-1-55-beta-3/24295/3

---
I always thought the single column with `max-width = 60em` was a huge waste of space in landscape mode, so I added a responsive grid layout.

To better separate the graphs, I used the same `TitledContainer` component as in the deck options. This also paves the way for help modals in the stats screen in the future.

### CODE REVIEW

**Comment by kleinerpirat** [comment]
Also sorry for the hypocrisy re:
> ... no additional UI changes

But this is just reusing what we already got in other screens, so I don't think it will cause any trouble.

**Comment by dae** [comment]
Two issues I spotted:
- when there's only a single column, there's too much padding on top
- if I flick the mouse wheel to scroll down to the bottom, the last graph is truncated
2022-11-01T11:34:15,261609569+10:00
2022-11-01T11:34:23,317686838+10:00

**Comment by dae** [comment]
:rocket:

**Comment by dae** [comment]
Minor regression: there's a strange outline when typing tags into the tags area.

**Pull request merged**
