### PR TITLE
Finish #2070: Single overlay instead of per field 

### LINKED ISSUE #2089: Field name appears in the middle of the field
This occur when there is many fields and so I need to scroll

2022-09-25-200247_1235x1040_scrot

### PR DESCRIPTION
**Pull request by kleinerpirat**
Makes Henrik's work of #2070 mergeable.
Closes #2089.

## My changes
- fix double-border issue
- tweak appearance of focused fields: box-shadow doesn't change color, only border
- fix field labels overlapping with field content

---
@hgiesel miss you man. I hope everything is alright.

### CODE REVIEW

**Comment by dae** [comment]
Thanks for looking into this Matthias. And agreed, hope you're well and in good spirits @hgiesel, and have just become busy.

**Comment by abdnh** [comment]
This has broken the fields.

image

Maybe this a clue (though adjusting the height to a valid value doesn't seem to make a difference).
image

**Comment by dae** [comment]
They work for me on both Qt 5+6. Ruled out add-ons?

**Comment by kleinerpirat** [comment]
The `height = NaNpx` probably stems from my use of `display: none` to fix the double-border issue Henrik mentioned in his original PR. Does Qt use a different web engine on Windows?

**Comment by abdnh** [comment]
> Ruled out add-ons?

Yes.

**Comment by abdnh** [comment]
I found an actual clue. The issue only happens with the "Reduce motion" option enabled.

**Comment by kleinerpirat** [comment]
Thanks for investigating, Abdo!
I'll look into this.

**Pull request merged**
