### PR TITLE
Update to use the new version of actions/cache

### PR DESCRIPTION
**Pull request by evandrocoan**
Networking issues impacting cache save/restore
https://github.com/actions/cache/issues/267

### CODE REVIEW

**Comment by dae** [comment]
Thanks for keeping on top of these Evandro. Is the debugging code from yesterday still required, or should I revert it?

**Comment by evandrocoan** [comment]
Before reverting we need to wait until the error `` can't find crate for `prost_derive` which `prost_build` depends on `` which happened on the pull request (https://github.com/ankitects/anki/pull/728) happens again.

If in some months it does not happens anymore, then, we could revert it because it could be that something random just went wrong on the cache unpacking.

But if you would like to not have that long Mac OS build running, we can try reverting it and let that code over a pull request. Once it happens again, we can try to replicate it over that pull request.

**Comment by dae** [comment]
Error's back: https://github.com/ankitects/anki/runs/1010643070

**Comment by evandrocoan** [comment]
I tried to run diff with a good cache and bad cache, but there were too my differences (due to bumped hashes being used as directories names by Rust). 

Let's hope that using GNU tar fixes it.

**Pull request merged**
