### PR TITLE
Add rename method to TagManager

### PR DESCRIPTION
**Pull request by BlueGreenMagick**
As noted in #586, I'm planning to add a context menu to the deck browser sidebar tree view. It'd be great if tags could be renamed, instead of having to bulk add, then bulk delete the tags.

If you plan to accept my PR, please scrutinize over my changes more than usual. I have close to zero knowledge in db, and pretty much just copied over the code from bulkAdd.

### CODE REVIEW

**Comment by dae** [comment]
Might be a while before I can return to this one

**Comment by dae** [comment]
The bulkAdd code is likely to be moved into Rust in the future, and it would make sense to do this code there as well. So while I'll hold off on merging the Python code, I'll leave this open as a reminder.

**Comment by dae** [comment]
Please give bulk_update() in master a test

**Comment by BlueGreenMagick** [comment]
As far as I can tell, it works great! It is going to be incredibly useful. (When it gets added to the gui)

**Pull request closed without merging**
