### PR TITLE
Add fuzzing setup

### PR DESCRIPTION
**Pull request by agentydragon**
I think this might be useful to verify some edge cases in template parsing.

I've uncovered at least one crash, triggered by trying to render this template: `{{=::HzolkMc{{ 1:}Wnqk\}}`

(It would be useful to track that crash in an issue... it would be useful to have GitHub issues enabled.)

### CODE REVIEW

**Comment by agentydragon** [comment]
(Sidenote: I think it's a bad idea to use a sequence of regexes to parse templates and it should probably be turned into an actual parser.

Another thing which makes it a little complicated is that Anki's templates are a language built on top of a language - Anki fields, conditionals etc. on top of HTML. If I designed something like that anew, my first thought would be "let's create a few custom HTML tags representing condtionals and fields, parse the DOM in the first HTML parser we find and manipulate the DOM accordingly to insert the custom fields". But Anki's template language is what it is and changing it would just create more confusion...)

**Comment by dae** [comment]
The current template code was introduced about 9 years ago, and at that time there were still Anki clients that didn't use HTML to render cards. The templating code was chosen at the time because it supported multiple platforms (https://mustache.github.io/), and could be used with only minor modifications.

I agree the regex approach is bad, which is why I implemented a parser in template.rs :-) It should be feasible to extend this to rendering cards in the future as well - the only challenge is preserving the ability for add-ons to provide their own field modifiers.

Because the templating code is likely to change in the future, it's probably not worth expending much effort on the current code. I'd suggest just catching all exceptions in the top level template function and returning 'invalid template' in that case - it will prevent the UI from getting stuck, and tide us through until a better solution is available. Appreciate the contribution though, and I'll leave this pull request around as the fuzzing may prove useful in the future.

Re an issue tracker, I moved away from a public issue tracker years ago, as the majority of issues people were posting were not actually bugs but just support requests, and it's easier to triage those on the support site.

**Comment by agentydragon** [comment]
I wonder whether there's a way on GitHub to make issue trackers writeable only by, say, organization members. That might give Anki the benefits of contributors knowing what needs to be done / reporting new issues without the high volume.

**Comment by evandrocoan** [comment]
@agentydragon, you have a bunch of binary files also included on this pull request. Should them to be added on `.gitignore`?

**Comment by agentydragon** [comment]
> @agentydragon, there are some binary files also included on this pull request. Shouldn't they to be added on `.gitignore`?

These are there on purpose - they are seeds for the fuzz tests the branch is adding.

**Comment by dae** [comment]
I tried this out on the latest code, but got stuck on an error message :

_pickle.PicklingError: Can't pickle <function template_cloze_text_fuzz at 0x7fb5083695e0>: it's not the same object as __main__.template_cloze_text_fuzz

The new template code is fairly straightforward and uses no unsafe code, so I'm not sure much could be revealed by fuzzing it, but if someone wants to prove me wrong, please feel free!

**Comment by dae** [comment]
Closing this for now

**Pull request closed without merging**
