### PR TITLE
Change sched values

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
I created an add-on which add a limit on the sum of new and rev cards by day. This needed to change the number of cards returned by those methods. Hence this add-on

### CODE REVIEW

**Comment by dae** [comment]
How about something like scheduler_did_get_review_limit_for_single_deck or schedule_review_limit_for_single_deck?

**Comment by Arthur-Milchior** [comment]
Done

**Comment by dae** [comment]
My apologies Arthur, I missed the 'r' in scheduler in the second example - it should be scheduler as schedule is a verb rather than a noun. The same 'Allows changing' comment from the other PR applies here as well. Otherwise looks good.

**Comment by dae** [comment]
Sorry again, today's changes have created a merge conflict

**Comment by dae** [comment]
(also may not need to pass in the scheduler for the new limit case, since they now share the same function?)

**Comment by Arthur-Milchior** [comment]
For consistency I entirely remove version number everywhere. Anyway, it can always be accessed by doing mw.col.scheds.name

**Comment by dae** [comment]
Thanks!

**Pull request merged**
