### PR TITLE
Cleanup 967

### PR DESCRIPTION
**Pull request by RumovZ**

### CODE REVIEW

**Comment by RumovZ** [comment]
Regarding the last commit, I realised that those translations should actually not be necessary. However, on my machine, Qt translations don't seem to work because all standard buttons have English labels. Is there something wrong in aqt/__init__.py?

**Comment by dae** [comment]
Please try with latest main

**Comment by RumovZ** [comment]
Thanks, it works now. 👍

**Comment by dae** [comment]
Thanks Rumo, looks good, and appreciate the typecheck change.

**Pull request merged**
