### PR TITLE
Hook init clayout

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Those are two kind of related change. The first hook is only here to correct something which is unclear in the hook list.

I intend to use this hook for https://ankiweb.net/shared/info/915063177 . Even if it will still lead to some monkey-patching. I don't see any way to create hook for all changes I make. 

If you are interested, I think it may be nice to merge this add-on in anki. Being able to preview easily how cards in different cloze may be nice. Especially since you can test for a specific card number in the template.

### CODE REVIEW

**Comment by dae** [comment]
"card_layout_will_show" would be more consistent

This is something that could be included in Anki, though I think the UI could be improved a bit. Instead of a spinner, perhaps a better approach would be to have the card type drop down be filled out with all the available cloze numbers, so the different cards are selected the same way as in a regular note type.

**Comment by Arthur-Milchior** [comment]
I certainly do agree that the UI is not beautiful. For my personal use I don't really pay attention, and I hope add-on users are fine with it. 
I agree that the list makes a lot of sens. Especially since a card number N won't be generated when you don't have a cloze N in one of the cloze field.

**Comment by Arthur-Milchior** [comment]
Name changed

**Comment by dae** [comment]
Cheers!

**Pull request merged**
