### PR TITLE
More precise percent of days studied

### PR DESCRIPTION
**Pull request by user1823**
https://forums.ankiweb.net/t/anki-23-12-beta/37771/101

I know that this is not a very necessary change and it makes the code longer. But, I feel that this is good to have. Obviously, you can disagree with me.

The proposed code works even when a single day is missed in over 50 years.

### CODE REVIEW

**Comment by user1823** [comment]
The test failed due to formatting issue. That can be corrected if you agree with the proposed solution.

**Review by chrislongros — APPROVED** [review]
I agree that the percentage should be more precise in > 99% ranges.

**Comment by dae** [comment]
I am ok with the proposed change if you can fix the code so that the tests pass.

**Comment by user1823** [comment]
I need some help.

The error message says:

> Error formatting /state/build/lin-ci/ankitects/anki-ci/ts/graphs/reviews.ts. Message: Expected ',', got ')' at /state/build/lin-ci/ankitects/anki-ci/ts/graphs/reviews.ts:382:46
>  
>            if (studiedPercent < 99.5) {            
> Had 1 error(s) formatting. Failed with code Some(1): /state/build/node_modules/.bin/dprint check

But, I don't think that there should be a comma after 99.5 in the above line.

**Comment by dae** [comment]
While I appreciate you making an effort to submit a PR instead of just a feature request, if you're unable to test and run them locally before submitting, there's not much of a difference unfortunately. Your syntax does not appear to be valid (it would be valid in Rust), and you appear to be returning a number in the 100 case instead of a string.

I asked ChatGPT to convert the code for you: 

```typescript
percent: (() => {
    if (studiedPercent < 99.5) {
      return localizedNumber(studiedPercent);
    } else if (studiedPercent < 99.95) {
      return localizedNumber(studiedPercent, 1);
    } else if (studiedPercent < 100) {
      return localizedNumber(studiedPercent, 2);
    } else {
      return '100';
    }
  })()
```

**Comment by user1823** [comment]
Ok, I accept that fixing this is not my cup of tea. If any other dev is willing to complete this, it would be great.

Also, sorry for the inconvenience caused. In the future, I will be careful to submit PRs only when I am almost 100% sure about the code working as intended.

**Comment by Luc-Mcgrady** [comment]
Sometimes the tests fail for no reason. This, to me, appears to be one of those times. 
Try and merge the base branch or force push to re-run the tests and see what happens.

**Comment by user1823** [comment]
@Luc-Mcgrady, you were absolutely right; the tests have passed now.

**Pull request merged**
