### PR TITLE
Slider easy day gui

### PR DESCRIPTION
**Pull request by Luc-Mcgrady**
Related forum post: https://forums.ankiweb.net/t/easy-days-ui-improvement-different-button-size/52665/10

image

### CODE REVIEW

**Comment by Expertium** [comment]
I think it's confusing that right now the titles go Normal -> Reduced -> Minimum, but after the update it will be Minimum -> Reduced -> Normal. But the benefit of making the order more clear (Minimum < Reduced) probably outweighs the immediate confusion, in the long run at least.

**Comment by Expertium** [comment]
Alternative: https://forums.ankiweb.net/t/easy-days-ui-improvement-different-button-size/52665/20?u=expertium
image

I'm curious which one people prefer

**Comment by Expertium** [comment]
Also, I still think that the order should be Normal -> Reduced -> Minimum and not Minimum <- Reduced <- Normal

**Comment by Expertium** [comment]
https://forms.gle/4BG1F3qhuahjkuC48
Feel free to participate, everyone!

**Review by abdnh — APPROVED** [review]

**Comment by dae** [comment]
Thanks everyone. Sadly the vote stacking does not surprise me - happens a fair bit on AnkiWeb too.

**Pull request merged**
