### PR TITLE
fix normal function

### PR DESCRIPTION
**Pull request by krmanik**
I have checked the issue. The issues are in normalization function, every time a new point added in polygon the points normalized with previous value which decrease the value till it get undefined. I have implemented this fix. But other issue is that when n number of polygon added in canvas in edit mode, only n-1 number of polygon saved. I tried to find the issue but still working on it.

### CODE REVIEW

**Comment by dae** [comment]
Hmm, I'm not sure this is the right approach. If a point happens to be on pixel 1, it's going to be normalized to 1, and moved all the way to the right/bottom, won't it?

**Comment by dae** [comment]
Maybe makeNormal/makeAbsolute should be changed to asNormal()/asAbsolute(), and have them return the modified values, instead of mutating the object?

**Comment by krmanik** [comment]
I guess I need help on this issue. Sorry.

**Comment by dae** [comment]
No problem. You're welcome to this one @abdnh if it interests you; if not, I'll try to look into this ~mid next week.

**Comment by abdnh** [comment]
I assume this was fixed in #2712?

**Comment by dae** [comment]
I think so, yep - thanks!

**Pull request closed without merging**
