### PR TITLE
Update to Qt 6.7

### PR DESCRIPTION
**Pull request by dae**
6.7.1+ adds a new subwheel, that we'll need to remove again come Qt 6.8

### CODE REVIEW

**Comment by dae** [comment]
The subwheel is problematic - if we don't blow away the pyenv first, it fails to be installed, and then importing fails:

```
dae@mb14:~% python3 -m venv ~/example

dae@mb14:~% example/bin/pip install pyqt6-webengine pyqt6-webengine-qt6==6.7.0 
Collecting pyqt6-webengine
  Using cached PyQt6_WebEngine-6.7.0-cp38-abi3-macosx_10_14_universal2.whl (388 kB)
Collecting pyqt6-webengine-qt6==6.7.0
  Downloading PyQt6_WebEngine_Qt6-6.7.0-py3-none-macosx_11_0_arm64.whl (98.6 MB)
     |████████████████████████████████| 98.6 MB 23.0 MB/s 
Collecting PyQt6>=6.2.0
  Using cached PyQt6-6.7.1-cp38-abi3-macosx_11_0_universal2.whl (11.9 MB)
Collecting PyQt6-sip<14,>=13.6
  Using cached PyQt6_sip-13.8.0-cp39-cp39-macosx_10_9_universal2.whl (110 kB)
Collecting PyQt6-Qt6<6.8.0,>=6.7.0
  Using cached PyQt6_Qt6-6.7.2-py3-none-macosx_11_0_arm64.whl (53.5 MB)
Installing collected packages: PyQt6-sip, PyQt6-Qt6, pyqt6-webengine-qt6, PyQt6, pyqt6-webengine
Successfully installed PyQt6-6.7.1 PyQt6-Qt6-6.7.2 PyQt6-sip-13.8.0 pyqt6-webengine-6.7.0 pyqt6-webengine-qt6-6.7.0
WARNING: You are using pip version 21.2.3; however, version 24.2 is available.
You should consider upgrading via the '/Users/dae/example/bin/python3 -m pip install --upgrade pip' command.

dae@mb14:~% example/bin/pip install --upgrade pyqt6-webengine-qt6 pyqt6-webenginesubwheel-qt6 
Requirement already satisfied: pyqt6-webengine-qt6 in ./example/lib/python3.9/site-packages (6.7.0)
Collecting pyqt6-webengine-qt6
  Using cached PyQt6_WebEngine_Qt6-6.7.2-py3-none-macosx_11_0_arm64.whl (26.2 MB)
Collecting pyqt6-webenginesubwheel-qt6
  Using cached PyQt6_WebEngineSubwheel_Qt6-6.7.2-py3-none-macosx_11_0_arm64.whl (72.4 MB)
Installing collected packages: pyqt6-webenginesubwheel-qt6, pyqt6-webengine-qt6
  Attempting uninstall: pyqt6-webengine-qt6
    Found existing installation: PyQt6-WebEngine-Qt6 6.7.0
    Uninstalling PyQt6-WebEngine-Qt6-6.7.0:
      Successfully uninstalled PyQt6-WebEngine-Qt6-6.7.0
Successfully installed pyqt6-webengine-qt6-6.7.2 pyqt6-webenginesubwheel-qt6-6.7.2
WARNING: You are using pip version 21.2.3; however, version 24.2 is available.
You should consider upgrading via the '/Users/dae/example/bin/python3 -m pip install --upgrade pip' command.

dae@mb14:~% ~/example/bin/python -c 'import PyQt6.QtWebEngineCore'                           
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/dae/example/lib/python3.9/site-packages/PyQt6/QtWebEngineCore.abi3.so, 0x0002): Library not loaded: @rpath/QtWebEngineCore.framework/Versions/A/QtWebEngineCore
  Referenced from: <A2E04B1B-3DFF-365F-B33A-BC4E51CD97E8> /Users/dae/example/lib/python3.9/site-packages/PyQt6/QtWebEngineCore.abi3.so
  Reason: tried: '/Users/dae/example/lib/python3.9/site-packages/PyQt6/Qt6/lib/QtWebEngineCore.framework/Versions/A/QtWebEngineCore' (no such file), '/Users/dae/example/lib/python3.9/site-packages/PyQt6/Qt6/lib/QtWebEngineCore.framework/Versions/A/QtWebEngineCore' (no such file)
zsh: exit 1     ~/example/bin/python -c 'import PyQt6.QtWebEngineCore'
```

For now, we'll either need to stick with Qt <= 6.7.0, update the build scripts to blow away the pyenv each time, or require devs to remove out/pyenv when updating.

**Comment by dae** [comment]
I think it's best we just wait until 6.8, due out at the end of Sep.

**Comment by dae** [comment]
About 1-2 weeks at current estimate, and allowing a week for PyQt: https://wiki.qt.io/Qt_6.8_Release

**Comment by NameLessGO** [comment]
https://www.qt.io/blog/qt-6.8-released 🚀

**Comment by twwn** [comment]
QT6.8 is already in Arch's testing repos. They just rebuilt PyQt6 6.7.1 rather than wait for its 6.8.

The latter might be reason why it breaks HTML media tags in Anki, e.g. for `<audio>`:

>Uncaught (in promise) DOMException: The element has no supported sources

**Comment by dae** [comment]
Nothing from PyQt yet.

**Comment by dae** [comment]
Unlikely to come soon:
https://www.riverbankcomputing.com/pipermail/pyqt/2024-October/046045.html

**Comment by dae** [comment]
Hopefully in a week or so:

https://www.riverbankcomputing.com/pipermail/pyqt/2024-December/046083.html

**Comment by dae** [comment]
Closing in favour of https://github.com/ankitects/anki/pull/3633

**Pull request closed without merging**
