### PR TITLE
Update to FSRS-rs v1.1.4 

### PR DESCRIPTION
**Pull request by L-M-Sherlock**
Related PR:
- https://github.com/open-spaced-repetition/fsrs-rs/pull/203
- https://github.com/open-spaced-repetition/fsrs-rs/pull/204
- https://github.com/open-spaced-repetition/fsrs-rs/pull/205

### CODE REVIEW

**Comment by dae** [comment]
Thanks as always Jarrett! I'll try to get to this tomorrow.

Regarding the upgrade to Rust 1.80, in the future, I'd prefer FSRS maintain a 'minimum Rust version' policy that allows us to go a few Rust versions back. There are some times when a Rust upgrade will break things (for example, dropping support for older OS versions), and if FSRS makes those changes before Anki is ready to, we won't be able to update to it.

**Comment by L-M-Sherlock** [comment]
OK. Should I revert the version for FSRS-rs for this PR?

**Comment by dae** [comment]
It's probably fine this time, just a comment for the future.

**Comment by dae** [comment]
Sorry for the delay!

**Comment by voczi** [comment]
Just a heads up: https://github.com/ankidroid/Anki-Android-Backend will need a similar toolchain update when the dependency is updated there (to rust ver 1.80)

**Pull request merged**
