### PR TITLE
Fix/fallback to non-manual entry when first_of_last_learn_entries non found

### LINKED ISSUE #3634: Set due date can confuse FSRS's calculations
> After updating to Anki 24.11, and re-optimising my parameters, some of my cards have had their intervals increased by an extremely large amount of time, for no apparent reason. For example, in the image below, you can see a card that before I rescheduled had an interval of 27 days. However, after updating to Anki 24.11 (and so FSRS 5), and rescheduling my cards, the interview changed to 6.67 years. I most definitely do not know this card, and a select few other cards that have had similar changes to their intervals.

Originally reported on https://forums.ankiweb.net/t/fsrs-5-increased-interval-by-5-years/53003/7

### PR DESCRIPTION
**Pull request by L-M-Sherlock**
fix #3634

### CODE REVIEW

**Comment by user1823** [comment]
Just to be sure, `non_manual_entries.is_some()` is true only if there are non-manual entries after the Reset entry, right?

Did you try this on a card that has no entries after a reset entry?

**Comment by L-M-Sherlock** [comment]
Sure:

image

**Comment by L-M-Sherlock** [comment]
Wait a minute... The `single_card_revlog_to_items` is too complex than my thoughts... The current implementation uses the first non-manual entry instead of the first non-manual entry after the `Reset` entry. I will fix it.

**Comment by L-M-Sherlock** [comment]
@dae, sorry for bothering you, but I don't understand this snippet of code:

https://github.com/ankitects/anki/blob/d90050600316cd58d25bc7f61fc762c3f704c101/rslib/src/scheduler/fsrs/params.rs#L289-L300

What's the aim of it?

**Comment by dae** [comment]
Introduced in https://github.com/ankitects/anki/commit/db93939ded947d74bb25bd8552a2b2356a096509. 

I believe the goal was to treat them as complete even if no learning entries have been found, if they started with a reschedule?

**Comment by user1823** [comment]
Dae added that code to implement my suggestion in https://github.com/open-spaced-repetition/fsrs4anki/issues/540#issuecomment-1848833376

The issue: https://github.com/open-spaced-repetition/fsrs4anki/issues/557

If the user uses Set Due Date to introduce a card rather than by normal way, the cards were getting very high difficulty.

**Comment by L-M-Sherlock** [comment]
My PR will infer the memory state from the first non-manual entry aftet `Reset` and set revlogs_complete to false. But this snippet of code will reverse my operation in some cases.

**Comment by user1823** [comment]
In https://github.com/open-spaced-repetition/fsrs4anki/issues/675, I suggested removing this snippet. So, I think that you can remove it.

**Comment by L-M-Sherlock** [comment]
OK, here is the next problem:

https://github.com/ankitects/anki/blob/d90050600316cd58d25bc7f61fc762c3f704c101/rslib/src/scheduler/fsrs/memory_state.rs#L287-L299

I think `first_review` should be extracted from the items returned by `single_card_revlog_to_items` instead of the original review entries.

**Comment by user1823** [comment]
> I think first_review should be extracted from the items returned by single_card_revlog_to_items instead of the original review entries.

Your suggestion seems reasonable to me.

**Comment by L-M-Sherlock** [comment]
So this unit test should be removed.

https://github.com/ankitects/anki/blob/d90050600316cd58d25bc7f61fc762c3f704c101/rslib/src/scheduler/fsrs/memory_state.rs#L397-L421

**Comment by L-M-Sherlock** [comment]
OK, the next problem:

https://github.com/L-M-Sherlock/anki/blob/35fa731b75b476ea730e7c2f38725d353143faef/rslib/src/scheduler/fsrs/params.rs#L328-L332

https://github.com/L-M-Sherlock/anki/blob/35fa731b75b476ea730e7c2f38725d353143faef/rslib/src/scheduler/fsrs/params.rs#L266-L272

If we find a relearning entry, should we set the revlogs_complete to true?

**Comment by user1823** [comment]
> If we find a relearning entry, should we set the revlogs_complete to true?

What did the previous code do? I will have to search through previous discussions for reasoning for/against this. Unfortunately, I won't be able to devote much time today and tomorrow.

**Comment by user1823** [comment]
On a gross overview, the changes made till now look good to me.

**Comment by L-M-Sherlock** [comment]
Here is the previous code:

https://github.com/ankitects/anki/blob/d90050600316cd58d25bc7f61fc762c3f704c101/rslib/src/scheduler/fsrs/params.rs#L327-L338

It was introduced in 90b0c6d84072ec0b11a43bd063a40cd1b784bdb0

**Comment by user1823** [comment]
If the previous code set it to true, then let's keep it that way. There must be some reason why it was done like that.

**Comment by L-M-Sherlock** [comment]
> If the previous code set it to true, then let's keep it that way. There must be some reason why it was done like that.

In previous code, `revlogs_complete` is true only when Anki finds the `first_of_last_learn_entries` or the first entry is Manual or Rescheduled.

**Comment by L-M-Sherlock** [comment]
If `revlogs_complete` is false, Anki will infer the memory state from the relearn entry. If it's true, the rating of the relearn entry will be treated as the first rating.

**Comment by user1823** [comment]
Does this PR also fix https://github.com/ankitects/anki/issues/2921?

**Comment by user1823** [comment]
A minor suggestion:

Bring this comment
```
// the revlog has been truncated, but not fully
```
between the following two lines in params.rs
```rs
        } else if let Some(first_non_manual_entry) = filtered_entries.first() {
            let first_review = FirstReview {
```

**Comment by L-M-Sherlock** [comment]
> Does this PR also fix #2921?

Yes. The `starting_state` is converted from the first review of that affected card.

**Comment by L-M-Sherlock** [comment]
> But, what does [90b0c6d](https://github.com/ankitects/anki/commit/90b0c6d84072ec0b11a43bd063a40cd1b784bdb0) do?

If the `first_of_last_learn_entries` is non-found, Anki will try to find the `first_relearn_entry`. If it's found, Anki will remove all entries before this entry. In the commit version, the `first_relearn_entry` was treated as the first learning entry. Its rating was used to generate the initial stability and difficulty.

**Comment by user1823** [comment]
> Its rating was used to generate the initial stability and difficulty.

Using normal formula or using memory_state_from_sm2?

**Comment by L-M-Sherlock** [comment]
> Using normal formula or using memory_state_from_sm2?

Using normal formula. But it was changed in db93939ded947d74bb25bd8552a2b2356a096509. This commit introduced `revlogs_complete`. And `revlogs_complete` is true only when `last_learn_entry` is found. If `revlogs_complete` is false, Anki will use `memory_state_from_sm2`.

**Comment by user1823** [comment]
> But it was changed in https://github.com/ankitects/anki/commit/db93939ded947d74bb25bd8552a2b2356a096509.

Well, in that case, using `memory_state_from_sm2` was a bug. But, this change was made 1 year ago and no one has complained. So, let's keep `revlogs_complete` as False in that case for now.

**Comment by user1823** [comment]
Next issue:

In the following code, if there are no learn entries, no review is ignored.

https://github.com/ankitects/anki/blob/f91dec44eed7051248f16115b8d575c17b5a238d/rslib/src/scheduler/fsrs/params.rs#L310-L327

Solution: (pseudocode)

```rs
 } else { 
     // While reviewing if the first learning step is before the ignore date, 
     // ignore every review before and including the last learning step 
     if let Some(idx) = first_of_last_learn_entries { 
         if entries[idx].id.0 < ignore_revlogs_before.0 && idx < entries.len() - 1 { 
             let last_learn_entry = entries 
                 .iter() 
                 .enumerate() 
                 .rev() 
                 .find(|(_idx, e)| e.review_kind == RevlogReviewKind::Learning) 
                 .map(|(idx, _)| idx); 
  
             entries.drain(..(last_learn_entry? + 1)); 
             revlogs_complete = false; 
             first_of_last_learn_entries = None; 
         } 
     } else if first_of_last_learn_entries.is_none() {
           delete entries with id < ignore_revlogs_before
         } 
 } 

```

**Comment by L-M-Sherlock** [comment]
Wait a minute:

In the current pull request, if we identify both a relearn entry and a non-manual entry, with the non-manual entry preceding the relearn entry, we infer the memory state from the relearn entry rather than the non-manual entry.

Is it expected?

**Comment by user1823** [comment]
> we infer the memory state from the relearn entry rather than the non-manual entry. Is it expected?

No

**Comment by L-M-Sherlock** [comment]
OK, so we need to remove the `first_relearn_entries` and related code.

**Comment by user1823** [comment]
I think that we should remove `or(first_relearn_entries)` from the following. WDYT?

```rs
    if let Some(idx) = first_of_last_learn_entries.or(first_relearn_entries) {
        // start from the (re)learning step
        if idx > 0 {
            entries.drain(..idx);
        }
```

**Comment by L-M-Sherlock** [comment]
> In the following code, if there are no learn entries, no review is ignored.

OK, we have a new problem:

**Comment by user1823** [comment]
> We need to break this loop when the entry is before the ignore date:

No,

What if we have something like 
```
L L | L L R
```
If we break the loop, we can't distinguish this case from something like ` | L L R R `. The current code distinguishes between these two cases.

Here, | is the ignore date.

**Comment by user1823** [comment]
Another thing:

In this PR, you added
```rs
    } else if let Some(idx) = non_manual_entries {
        // if there are no learning entries but there are non-manual entries,
        // we ignore all entries before the first non-manual entry
        if idx > 0 {
            entries.drain(..idx);
        }
```

Is this required? The code immediately after this is already removing all the manual entries.

**Comment by user1823** [comment]
> What if the non-manual entry is before the ignore date?

Ignore that entry. That's what I wrote in my pseudocode.

**Comment by user1823** [comment]
> This code is used to remove entries before Reset.

I assume that by "this code", you mean the code you added.

Then what does the `break` do in the following code?

```rs
            // If we find a `Learn` entry after the `Reset` entry, we should
            // ignore the entries before the `Reset` entry
            if first_of_last_learn_entries.is_some() {
                revlogs_complete = true;
                break;
            // If we find a non-manual entry after the `Reset` entry, we should
            // ignore the entries before the `Reset` entry
            } else if non_manual_entries.is_some() {
                revlogs_complete = false;
                break;
```

**Comment by user1823** [comment]
Ok, I guess that I am now understanding the purpose of this code.

Even if the loop breaks, the entries are still there. If we don't remove them, `first_non_manual_entry` in memory_state.rs will be incorrect. Right?

If I am correct, I suggest moving that code just after the loop ends, i.e., just before

```rs
    if training {
        // While training ignore the entire card if the first learning step of the last
```

**Comment by user1823** [comment]
Next issue/suggestion:

We should also exclude cram revlogs (entry.review_kind == RevlogReviewKind::Filtered && entry.ease_factor == 0) here.

```rs
        if matches!(entry.button_chosen, 1..=4) {
            non_manual_entries = Some(index);
        }
```

This is the last suggestion from me for today. I will take another look tomorrow to ensure that no issue is remaining and then we can request dae for a final review.

By the way, thanks for this PR. You have squashed tons of bugs with this.

**Comment by L-M-Sherlock** [comment]
I refactored a lot of codes.

# Cram revlogs are skipped

```rust

    for (index, entry) in entries.iter().enumerate().rev() {
        if entry.review_kind == RevlogReviewKind::Filtered && entry.ease_factor == 0 {
            continue;
        }
```
# Only search the first non-manual revlog entry after ignore date

```rust
        if matches!(entry.button_chosen, 1..=4) && entry.id.0 > ignore_revlogs_before.0 {
            non_manual_entries = Some(index);
        }
```

# fallback to non-manual revlog entry if the first of last learn entires is before ignore date

I referred to your idea: https://github.com/ankitects/anki/pull/2922#issuecomment-1937037115

```
        // While reviewing if the first learning step is before the ignore date,
        // fallback to non_manual_entries
        if let Some(idx) = first_of_last_learn_entries {
            if entries[idx].id.0 < ignore_revlogs_before.0 && idx < entries.len() - 1 {
                revlogs_complete = false;
                first_of_last_learn_entries = None;
            }
        }
```

**Comment by dae** [comment]
Sorry, I forgot we iterate on the entries in reverse, which I think has made my renaming incorrect. Reviewing...

**Comment by dae** [comment]
Ok, sorry about the delay. Tests past after the changes in the last commit, but I'm not 100% confident the behaviour is identical - can you spot any problems?

**Comment by L-M-Sherlock** [comment]
For this case, the `revlog_complete` should be false.

```
L | L R
```

**Comment by user1823** [comment]
The last commit (https://github.com/ankitects/anki/pull/3639/commits/7fd9a7789efe8e9633bac66f526ab8456974c3aa) has introduced a functional change (I think) and it isn't desirable.

If a card has revlog entries like `L L | L R R`, this card
- is used for training
- gets it memory states using normal FSRS formulas (instead of memory_states_from_sm2) at the L entry just after the cutoff.

where | = cutoff date

**Comment by user1823** [comment]
Apart from the above mentioned functional issue, the code looks good to me.

However, I have some suggestions regarding wording:

memory_state.rs
- rename `first_non_manual_entry` to `first_user_graded_entry` (or something like that)
- change this comment
```
        // but if there's only a single revlog entry, we'll fall back on the first
        // non-manual entry
```
to 
```
        // cards with a single review-type entry also get memory states from revlog rather than card states
```

params.rs
- change this comment
```
        // While reviewing, if the first learning step is before the ignore date,
        // we won't start from the learning step.
```
to 
```
        // While reviewing, if the first learning step is before the ignore date,
        // infer memory states from sm2 at the revlog entry just after.
```
- change this comment
```
        // if there are no learning entries, but the user has reviewed the card,
        // we ignore all entries before the first grade
```
to 
```
        // ignore all entries before the first user-graded rating matched by the loop
```

**Pull request merged**
