### PR TITLE
Fix height misalignment of legacy buttons

### PR DESCRIPTION
**Pull request by hgiesel**
Another approach to #1194.

@kleinerpirat Could you have a look this covers all your cases? Specifically, I removed this line: ` filter: invert(1) grayscale(1) brightness(100)`. I couldn't quite see what was its purpose, and it removed the color of the color selector from "Mini format pack" upon `:active` state.

### CODE REVIEW

**Comment by kleinerpirat** [comment]
Thank you for the elegant restructuring, Henrik!

The following misalignment is caused by your usage of `height` instead of `min-height`:
image

---

The purpose of `filter: invert(1) grayscale(1) brightness(100)` was to imitate the effect of the Svelte buttons in day mode as best as I could.
Compare clicking and holding a default button and an add-on button in day mode in this PR and you will see that they differ. The default buttons invert their color while the legacy buttons stay the same.
`grayscale(1) brightness (100)` was meant to ensure that it is white.

Screenshot from 2021-05-25 15-49-20

With my first PR I wanted to create a perfect replica of the Svelte buttons, but perhaps that's not necessary.

**Comment by hgiesel** [comment]
> Compare clicking and holding a default button and an add-on button in day mode in this PR and you will see that they differ. The default buttons invert their color while the legacy buttons stay the same.

Are you sure, that's not the effect of some add-on? I cannot recreate it on my side.

Screenshot 2021-05-25 at 20 32 42

**Comment by kleinerpirat** [comment]
Yes, I'm positive. I disabled all the add-ons and it looks like this on my Linux system:

buttons

**Comment by hgiesel** [comment]
@kleinerpirat 
Hm, I cannot recreate this on my Mac. I also cannot recreate if I change the `isMac` `isLin` `isWin` selectors in the HTML. Very mysterious...

**Comment by kleinerpirat** [comment]
Not a big deal i guess :D

If it shouldn't be there by default, it was certainly for the best that you removed the filter 👍🏻

I didn't notice any other issues with this PR.

Thanks again for the help with this! I can't wait for the other users to see the shiny new buttons ☺️

**Comment by hgiesel** [comment]
I guess you didn't see my Edit:

Looking at it through the Web Inspector, can you tell the HTML file it comes from. The selectors should have the file of origin next to them. Could you have a look there?

Screenshot 2021-05-25 at 22 23 27

I'd still be interested in where the color comes from...

**Comment by kleinerpirat** [comment]
Ah yes, I didn't see the edit because GitHub on the phone doesn't refresh automatically.

As you can see, I got a mysterious button styling coming out of nowhere:

image

With all add-ons except WebView inspector disabled, this is very odd indeed...

**Comment by hgiesel** [comment]
Then this must be part of the base CSS. I'm not even sure who exactly provides it: the OS, Chromium, or Qt?

Also not sure whether to consider this something to fix: what would you say, @dae?

**Comment by dae** [comment]
It's probably part of the Qt or Chromium theme, and I see it on an Ubuntu 18 system here as well, so I'm guessing it affects all/many Linux users, so it would be nice to fix if we can do so in a clean way. Could we just specify the color for hover/active explicitly instead, with a comment that it's required to override the default on Linux?

**Pull request merged**
