### PR TITLE
[IO API] Create Python entry points for creating and editing IO notes

### PR DESCRIPTION
**Pull request by glutanimate**
A first small batch of changes to create the API surface that the new version of IOE will need. More to follow as I continue with the rework – the bulk of the work will lie on the JS/Svelte side.

This batch targets the python editor API, slightly refactoring the current IO-related methods and creating entry-point methods for adding and editing image occlusions that abstract the Py → JS comms implementation details away.

CC @krmanik @dae

### CODE REVIEW

**Comment by dae** [comment]
Looks good in isolation, but unfortunately has conflicted with Mani's recent changes. Mani's code assumes that the file picker function would be called on both add and edit paths, and your code is assuming it's only called for new notes, so will presumably need tweaking.

**Comment by glutanimate** [comment]
OK, updated and rebased against `main`.

NB: Merging this PR would re-enable IO, so let's defer it until 2.1.66 is released, or if the release is likely to take longer and @krmanik and I need to work on IO things in parallel, let's merge it into an IO feature branch perhaps.

**Comment by dae** [comment]
Release is out :rocket:

**Comment by dae** [comment]
Your recent PRs are failing when merged - eg https://buildkite.com/ankitects/anki-ci/builds/6166#018a2565-c300-4559-a029-fa20a10581d5. Would you mind doing a quick PR that adds an edit to CONTRIBUTORS from GitHub's interface?

**Comment by glutanimate** [comment]
[Done](https://github.com/ankitects/anki/pull/2623)! Looks like GH switched my account over to the new ID-based noreply format.

**Pull request merged**
