### PR TITLE
Fix wrong stock note type being used

### PR DESCRIPTION
**Pull request by abdnh**
Reported in https://forums.ankiweb.net/t/anki-2-1-45-alpha/10061/49

### CODE REVIEW

**Comment by abdnh** [comment]
The fix for the recent black issue on Windows doesn't seem to work for me by the way:

```
==================== Test output for //pylib:format_check:
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "c:\python\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "c:\python\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "\\?\D:\bazel\anki\d63ysmdv\execroot\net_ankiweb_anki\bazel-out\x64_windows-fastbuild\bin\pylib\format_check.exe.runfiles\pypi__38__black_21_5b0\black\__init__.py", line 87, in <module>
    CACHE_DIR = Path(user_cache_dir("black", version=__version__))
  File "\\?\D:\bazel\anki\d63ysmdv\execroot\net_ankiweb_anki\bazel-out\x64_windows-fastbuild\bin\pylib\format_check.exe.runfiles\pypi__38__appdirs_1_4_4\appdirs.py", line 
293, in user_cache_dir
    path = os.path.normpath(_get_win_folder("CSIDL_LOCAL_APPDATA"))
  File "\\?\D:\bazel\anki\d63ysmdv\execroot\net_ankiweb_anki\bazel-out\x64_windows-fastbuild\bin\pylib\format_check.exe.runfiles\pypi__38__appdirs_1_4_4\appdirs.py", line 
481, in _get_win_folder_with_pywin32
    dir = shell.SHGetFolderPath(0, getattr(shellcon, csidl_name), 0, 0)
pywintypes.com_error: (-2147024893, 'The system cannot find the path specified.', None, None)
\\?\D:\bazel\anki\d63ysmdv\execroot\net_ankiweb_anki\bazel-out\x64_windows-fastbuild\bin\pylib\format_check.exe.runfiles\net_ankiweb_anki\pylib\tests\..
================================================================================
ERROR: D:/dev/anki/repo/qt/aqt/BUILD.bazel:7:8: Executing genrule //qt/aqt:hooks_gen failed: (Exit 1): bash.exe failed: error executing command C:/msys64/usr/bin/bash.exe 
-c source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/qt/genhooks_gui.exe bazel-out/x64_windows-fastbuild/bin/qt/aqt/hooks_gen.py
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "c:\python\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "c:\python\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "\\?\D:\bazel\anki\d63ysmdv\execroot\net_ankiweb_anki\bazel-out\host\bin\qt\genhooks_gui.exe.runfiles\pypi__38__black_21_5b0\black\__init__.py", line 87, in <module>
    CACHE_DIR = Path(user_cache_dir("black", version=__version__))
  File "\\?\D:\bazel\anki\d63ysmdv\execroot\net_ankiweb_anki\bazel-out\host\bin\qt\genhooks_gui.exe.runfiles\pypi__38__appdirs_1_4_4\appdirs.py", line 293, in user_cache_dir
    path = os.path.normpath(_get_win_folder("CSIDL_LOCAL_APPDATA"))
  File "\\?\D:\bazel\anki\d63ysmdv\execroot\net_ankiweb_anki\bazel-out\host\bin\qt\genhooks_gui.exe.runfiles\pypi__38__appdirs_1_4_4\appdirs.py", line 481, in _get_win_folder_with_pywin32
    dir = shell.SHGetFolderPath(0, getattr(shellcon, csidl_name), 0, 0)
pywintypes.com_error: (-2147024893, 'The system cannot find the path specified.', None, None)
Traceback (most recent call last):
  File "\\?\D:\bazel\anki\d63ysmdv\execroot\net_ankiweb_anki\bazel-out\host\bin\qt\genhooks_gui.exe.runfiles\net_ankiweb_anki\qt\tools\genhooks_gui.py", line 941, in <module>
    write_file(path, hooks, prefix, suffix)
  File "\\?\D:\bazel\anki\d63ysmdv\execroot\net_ankiweb_anki\bazel-out\host\bin\qt\genhooks_gui.exe.runfiles\net_ankiweb_anki\pylib\tools\hookslib.py", line 169, in write_file
    subprocess.run([sys.executable, "-m", "black", "-q", path], check=True)
  File "c:\python\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['c:\\python\\python.exe', '-m', 'black', '-q', 'bazel-out/x64_windows-fastbuild/bin/qt/aqt/hooks_gen.py']' returned non-zero exit 
status 1.
```

**Comment by RumovZ** [comment]
Both the msys and the Windows home directories work for me. Strange. I can see that your bazel is on a different drive, maybe that's got something to do with it?
I used the msys directory because it's available at runtime, but the Windows one is not. I assume `os.environ["USERPROFILE"] = os.environ["HOME"].replace("msys64\\home", "users")` would work for you?

**Comment by abdnh** [comment]
> maybe that's got something to do with it?

Hmm, maybe.


> I assume `os.environ["USERPROFILE"] = os.environ["HOME"].replace("msys64\\home", "users")` would work for you?

I just found out that different environments can used for each format check when running `bazel test` (e.g. sometimes HOME will be something like `D:/bazel/anki/d63ysmdv/execroot/net_ankiweb_anki/_tmp/a2bc3091f8f07ba237fc1c7105f526c6`), so this is not foolproof.

**Comment by dae** [comment]
Thanks for the fix Abdo!

Re the black issue, does this work for you both?

```patch
diff --git a/pylib/tools/hookslib.py b/pylib/tools/hookslib.py
index ab499c896..c63d3046e 100644
--- a/pylib/tools/hookslib.py
+++ b/pylib/tools/hookslib.py
@@ -8,6 +8,7 @@ Code for generating hooks.
 import os
 import subprocess
 import sys
+import tempfile
 from dataclasses import dataclass
 from operator import attrgetter
 from typing import List, Optional
@@ -163,7 +164,7 @@ def write_file(path: str, hooks: List[Hook], prefix: str, suffix: str):
 
     # work around issue with latest black
     if sys.platform == "win32" and "HOME" in os.environ:
-        os.environ["USERPROFILE"] = os.environ["HOME"]
+        os.environ["USERPROFILE"] = tempfile.gettempdir()
     with open(path, "wb") as file:
         file.write(code.encode("utf8"))
     subprocess.run([sys.executable, "-m", "black", "-q", path], check=True)
```

If so, a similar change will need to be made to the two run_format files as well

**Comment by abdnh** [comment]
Nothing seems to work for me except setting both USERPROFILE and HOME to `C:\Users\abdo`. I will use this workaround for now, or try compiling from the C drive.

**Pull request merged**
