### PR TITLE
NF: Improve typing of AnkiWebView action

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
There are only two types of actions. The code does not seems to consider this to be extandable, and the changed variable is private, so I would expect it relatively acceptable to change the way it work. This would improve the typing.

If this is rejected, at least, the callback should be noted as optional, so that the IDE does not complain that `if cb` can not be false.

==========

I should note that `./ninja format` failed with 

```
failed: format:dprint
[dprint-plugin-prettier]
Shutting down due to error: failed to fill whole buffer
Shutting down due to error: failed to fill whole buffer
Error resolving plugin https://plugins.dprint.dev/prettier-0.46.1.json: Failed plugin schema verification. This may indicate you are using an old version of the dprint CLI or plugin and should upgrade.: The plugin schema version was 5, but expected 4.
Failed with code Some(1): /home/milchior/anki/out/node_modules/.bin/dprint fmt
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.07s
     Running `out/rust/debug/configure`
```

I don't understand why easily, but it seems that the py files still were formatted correctly

### CODE REVIEW

**Comment by dae** [comment]
Unsure about that error, but it looks like mypy is failing with a different one (maybe Action needs to be qualified with the class name?)

**Comment by Arthur-Milchior** [comment]
After pulling a fresh copy of anki, ninja works again.

**Comment by Arthur-Milchior** [comment]
Actually, just using a callable seems fine enough

**Comment by dae** [comment]
That's more elegant - thanks!

**Comment by glutanimate** [comment]
It looks like the change here [broke Image Occlusion Enhanced](https://forums.ankiweb.net/t/anki-24-10-beta/49989/202?u=glutanimate). Although I'm not a fan of holding back thoughtful code quality and typing improvements like this for the sake of add-ons, would it be possible to revert this change for now? IOE is on its slow way out, but there is still a large of proportion of Anki users using it, and since this change is largely DX-focused, I think it's justifiable to hold it back in order to avoid users not being able to upgrade due to IOE incompatibility.

FWIW, I created an issue on IOE's tracker to move away from the reliance on these APIs, but it will likely take a bit of time for me to look into this (not to mention for any change to actually reach users), so a revert or switch to a more conservative refactoring for now would be much appreciated :pray:  https://github.com/glutanimate/image-occlusion-enhanced/issues/316

**Pull request merged**
