### PR TITLE
polish graphs of simulator, true retention table and forgetting curve

### PR DESCRIPTION
**Pull request by L-M-Sherlock**
Source: https://forums.ankiweb.net/t/anki-24-10-beta/49989/23?u=l.m.sherlock

Simulator: “Simulation” is not cut off now.

image

True retention: the width is more adaptive.

image<br/>

image<br/>

image

Forgetting curve: don't display time, only date when the total elapsed time is >=365 days AND the currently selected timeframe is either “First year”.

image

image

also fix: 
- #3453

### CODE REVIEW

**Comment by Expertium** [comment]
image
Stability and retrievability in the graph don't match the ones at the top of Card Info.
I could _maybe_ write the difference in retrievability off as a rounding error, but stability is definitely wrong.

**Comment by Expertium** [comment]
Ok, here's an actual problem:
https://imgur.com/hsW6N2o

The last segment of the forgetting curve makes the mouse and the pop-up window with stats glitch

**Comment by brishtibheja** [comment]
Can we not divide the true retention table into three parts and have radio buttons to switch between them? Thoughts?

**Comment by Expertium** [comment]
> Can we not divide the true retention table into three parts and have radio buttons to switch between them? Thoughts?

Idk, I'm not sure that it's a good idea, but I'm not sure if it's a bad idea either. @user1823 thoughts?

**Comment by brishtibheja** [comment]
@Expertium It can be done only on narrow devices if possible. IMO it's better than scrolling. But, on wider screens, do you really need to see everything at once or is it better to have limited info on focus? This is the crux we need to consider even for narrow screen.

It's fine if Sherlock doesn't want to do it if it can be done later. I want to hear dae's opinions.

**Comment by user1823** [comment]
> It can be done only on narrow devices if possible. IMO it's better than scrolling. 

I agree. If we can't fit whole table on the screen, having radio buttons to switch is better than scrolling.

**Comment by voczi** [comment]
Two questions for the simulator:
1) Do simulation days less than 25 work now with this PR?
2) Can you use something like 777 simulation days without the bottom axis labels overlapping with each other?
For 1) I had a solution of just doing Math.ceil(days, 7) in that one function where the graph is created. Not sure if this is right or not, but anyway, the original Math.round(days/50) will just result in 0 for days<25.
Although for 2) I was looking at the d3 docs for hours without finding a proper solution.

**Comment by L-M-Sherlock** [comment]
1) Thanks for your solution! It looks nice now.
image

2) I cannot reproduce the overlapping problem.
image

**Comment by voczi** [comment]
> 2\. I cannot reproduce the overlapping problem.

The graphs axis looks different now. So maybe it's gone.

**Comment by Expertium** [comment]
Btw, it might be worth doing some light theme - dark theme shenanigans because "dark on dark" is not good, UI-wise
The text and the curve should be white, or close to white
image

**Comment by L-M-Sherlock** [comment]
image

Done.

**Comment by Expertium** [comment]
The curve itself is still "dark on dark". How complicated would it be to define, say, 20 light colors for the dark theme and 20 dark colors for the light theme?

**Comment by L-M-Sherlock** [comment]
The choices are limited: https://d3js.org/d3-scale-chromatic/categorical

I'm not a professional UI designer. Suggestion is welcome.

**Comment by L-M-Sherlock** [comment]
image

I figure it out.

**Comment by voczi** [comment]
Everything looks a lot better now imo.

**Comment by dae** [comment]
The minimum width of the graph is still too wide unfortunately, so #3445 hasn't been solved yet. An easy way to test this locally is to start Anki with:

```
ANKI_API_HOST=0.0.0.0 ./run
```

Then in Chrome, surf to http://10.0.0.2:40000/graphs (or the IP address of your computer). You can then resize the window to see how it looks on a mobile screen. Or you can paste that URL into Safari on an iPhone, and see it displayed there.

Note how the other graphs have scrolled off to the right:

Screenshot 2024-10-01 at 12 06 49 am

Radio buttons were suggested earlier, and they're a reasonable solution if the user will typically only be looking at one of the tree (e.g. mature). If it's common for users to want to see all the data at once, perhaps it would be better to put the three tables in a flexbox, and have them automatically wrap on narrow devices, and display side by side on wider screens?

Thank you for all the hard work you've put into these fixes!

**Pull request merged**
