### PR TITLE
Set same font size for all platforms and make editor UI a bit smaller

### PR DESCRIPTION
**Pull request by kleinerpirat**
https://forums.ankiweb.net/t/anki-2-1-55-beta-3/24295/4

# Changes
- use base font size of 13px (macOS value) for all platforms
- decrement `1.6em` in various editor components to `1.5em`

## Before
image

## After
image

---
@dae Could you send me similar screenshots of Mac and Windows for comparison? :pray:

### CODE REVIEW

**Comment by dae** [comment]
Windows before->after, with native window for comparison:

2022-11-02T20:59:53,445536301+10:00
2022-11-02T21:00:55,644947092+10:00

**Comment by kleinerpirat** [comment]
Thanks! This looks to me like we should keep the separate size for Windows. On Linux, I prefer the macOS size.

**Comment by dae** [comment]
macOS before→after
shot-main
shot-pr

**Comment by kleinerpirat** [comment]
From my side this would be a go. How do you feel about the slightly smaller editor UI (`1.5em`)? Other than that, nothing will change on mac.

**Comment by dae** [comment]
The difference is quite subtle - I think the PR might be closer to the macOS defaults, but I'm not 100% sure :-)

**Pull request merged**
