### PR TITLE
added "Windows user (using PyCharm)" section to README.development

### PR DESCRIPTION
**Pull request by lukkea**
I made these notes for future me. Thought they might be helpful to get new Anki Windows PyCharm devs coding faster, but I realise they are more verbose than other notes in this file and may not be the style you are after.

The addition of requirement.txt may not be ideal (and I can remove) although it may be useful to others, not just Windows PyCharm devs...

### CODE REVIEW

**Comment by lukkea** [comment]
don't know why that could be failing.

the requirement.txt couldn't've broken it, could it?

**Comment by lukkea** [comment]
ah, ok. It's a problem with rsync.

I noticed the http://repo.msys2.org/ site was down ealier as I double checked my work on this. I guess the script is reaching out to there to get rsync?

If I'm right, I wonder if I can resubmit this when the site is back up, or whether I have to do a new pull request.

If anyone reads this and can advise I'd be grateful.

**Comment by abdnh** [comment]
> 
> 
> ah, ok. It's a problem with rsync.
> 
> I noticed the http://repo.msys2.org/ site was down ealier as I double checked my work on this. I guess the script is reaching out to there to get rsync?
> 
> If I'm right, I wonder if I can resubmit this when the site is back up, or whether I have to do a new pull request.
> 
> If anyone reads this and can advise I'd be grateful.

You don't have to resubmit it. It can be merged anyway.

**Comment by lukkea** [comment]
> > ah, ok. It's a problem with rsync.
> > I noticed the http://repo.msys2.org/ site was down ealier as I double checked my work on this. I guess the script is reaching out to there to get rsync?
> > If I'm right, I wonder if I can resubmit this when the site is back up, or whether I have to do a new pull request.
> > If anyone reads this and can advise I'd be grateful.
> 
> You don't have to resubmit it. It can be merged anyway.

great, thank you.

**Comment by dae** [comment]
Thank you for providing detailed instructions! It mostly looks fine, but distributing a separate requirements.txt that references packages Anki doesn't use is confusing. Anki's runtime dependencies are already defined in setup.py in the pylib and qt folders, and development dependencies are defined in requirements.dev. They are automatically installed when 'make run' is used.

**Comment by lukkea** [comment]
> Thank you for providing detailed instructions! It mostly looks fine, but distributing a separate requirements.txt that references packages Anki doesn't use is confusing. Anki's runtime dependencies are already defined in setup.py in the pylib and qt folders, and development dependencies are defined in requirements.dev. They are automatically installed when 'make run' is used.

Thanks for those pointers. I've removed the unused packages so only pipwin, lameenc, py-make, and python-gettext  are referenced now. pipwin is needed for pyaudio.

dev tested locally, and working fine.

If you would prefer me to remove the requirements.txt completely and just keep the manual list in the README.development notes just let me know!

**Comment by dae** [comment]
Sorry, I was not clear - I would prefer you don't include a separate requirements.txt. Are you sure those others are even required? pyaudio  can be grabbed from https://github.com/ankitects/windows-ci-tools), Anki does not use Python bindings for lame, and gettext bindings are included with Python. I'm also surprised py-make can handle Anki's makefiles.

**Comment by lukkea** [comment]
> Sorry, I was not clear - I would prefer you don't include a separate requirements.txt. Are you sure those others are even required? pyaudio can be grabbed from https://github.com/ankitects/windows-ci-tools), Anki does not use Python bindings for lame, and gettext bindings are included with Python. I'm also surprised py-make can handle Anki's makefiles.

That's ok, I think you probably were clear (but I misunderstood, sorry).

I'm a seasoned dev (dbase III+ & Clipper, to Delphi, on through raw web-dev, to .NET with C#, with limited Swift and Android) **but Python newbie**, so **_really_** appreciate your help with this.

I've stripped out all of that and it's just built now on my dev machine (that _may_ have artefacts from previous attempts); I'll get a clean vm/laptop later and make sure I've got it right and then update.

Thanks again.

**Comment by lukkea** [comment]
> Sorry, I was not clear - I would prefer you don't include a separate requirements.txt. Are you sure those others are even required? pyaudio can be grabbed from https://github.com/ankitects/windows-ci-tools), Anki does not use Python bindings for lame, and gettext bindings are included with Python. I'm also surprised py-make can handle Anki's makefiles.

That's all done and working. Thanks again for your help.

**Comment by dae** [comment]
All good - thanks!

**Pull request merged**
