### PR TITLE
Add zoom out and zoom in shortcuts

### PR DESCRIPTION
**Pull request by tatsumoto-ren**
Added missing keyboard shortcuts for zooming in and out, which can be handy while reviewing cards.

### CODE REVIEW

**Comment by dae** [comment]
Previous discussion: https://github.com/ankitects/anki/pull/1668#issuecomment-1043191227

**Comment by tatsumoto-ren** [comment]
> Previous discussion: #1668 (comment)

If I understand correctly, something else is conflicting with ctrl+plus and ctrl+minus?

**Comment by dae** [comment]
Two issues as far as I understand it: one of the shortcuts conflicts with the subscript or superscript shortcut in the browser, and the standard shortcuts are hard/impossible to type on some keyboard layouts.

**Comment by tatsumoto-ren** [comment]
Will close for now, as it seems there's an issue preventing the hotkeys from being available by default. As a workaround, the hotkeys can be enabled by installing one of the existing add-ons from AnkiWeb.

**Pull request closed without merging**
