### PR TITLE
Hook editor_note_will_load

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
A current problem I have is that there is nothing similar to hook inside of javascript. It seems that it would be easier to be able to add other methods in javascript and call them in loadNote. Currently I simply redefined loadNote, which is far from perfect

I am not sure at all that's the best way to achieve this feature. But I am sure that I want to execute some function when a note is loaded. In particular because add-ons changing the editor need to pass more informations to the code

### CODE REVIEW

**Comment by dae** [comment]
Please use 'editor_will_load_note' to match the existing 'editior_did_load_note', and "allows changing"

**Comment by Arthur-Milchior** [comment]
Changed
Merge conflict corrected

On master, I can't run "make check" anymore, it directly return "make: *** [Makefile:123: check] Error 127
"

**Comment by dae** [comment]
it still says "allow to change", and it looks like you've accidentally included package-lock.json changes. While you're fixing those issues, would you mind switching the editor and js arguments so editor comes first?

**Comment by dae** [comment]
(can't reproduce the makefile issue - could it be related to trailing whitespace?)

**Comment by dae** [comment]
(of course it's a filter - nevermind about the switching args comment :-)

**Pull request merged**
