### PR TITLE
Add an option to add a set of tags to notes updated on import

### PR DESCRIPTION
**Pull request by ErezVolk**
I frequently update a deck by re-importing a .tsv file. Right now, all I get is the count of updated notes, with no easy way to find those cards.

This adds to the import screen an option to add one or more tags to all cards modified during import.

image

### CODE REVIEW

**Comment by dae** [comment]
Perhaps that option should only appear/apply when the user has selected 'update existing notes'? Please also add yourself to the CONTRIBUTORS file.

**Comment by ErezVolk** [comment]
> Perhaps that option should only appear/apply when the user has selected 'update existing notes'? Please also add yourself to the CONTRIBUTORS file.

Excellent point. I'll disable the option when the mode isn't "update".

**Comment by dae** [comment]
Thanks Erez!

**Comment by ErezVolk** [comment]
Thank you! Anki has changed my life, what can I say :)

**Pull request merged**
