### PR TITLE
Keep previous FSRS parameters if they get worse when optimizing

### LINKED ISSUE #2972: Keep previous FSRS parameters if they get worse when optimizing
https://forums.ankiweb.net/t/measures-to-prevent-new-fsrs-parameters-from-being-worse-than-the-old-ones/38957

### PR DESCRIPTION
**Pull request by abdnh**
Closes #2972

### CODE REVIEW

**Comment by user1823** [comment]
If the older parameters are better, I think that we should show a message like "You already have optimal parameters."

https://github.com/ankitects/anki/issues/2972#issuecomment-1918738285

**Comment by dae** [comment]
Thanks Abdo, looks good.

@user1823 I'm not sure that's a good idea - there's a fairly high chance the user will sometimes get worse results, and such a message may make the user think there's something wrong and such behavior is not expected. @L-M-Sherlock any thoughts?

(merging as-is for now, but we can change this in a follow-up if need be)

**Comment by L-M-Sherlock** [comment]
It's not a matter of the user, so I don't want to display the message. Even if we display this message, the user has nothing could do to deal with that.

**Comment by user1823** [comment]
Personally, I would expect something to change if I press a button and see a progress happening. If nothing changes, I would wonder "Did the process not go to completion?"

But if both of you think that we should not add the message, then it's OK.

**Comment by Expertium** [comment]
> such a message may make the user think there's something wrong and such behavior is not expected.

I don't think that "You already have optimal parameters" sounds worrying. At least I wouldn't think that something went wrong. But I would definitely suspect that something's wrong if I clicked "Optimize" and the parameters didn't change. So I'm in favor of the message. We can make a poll on ankiforums.

**Pull request merged**
