### PR TITLE
Created the AnkiMediaQueue for JavaScript media support

### PR DESCRIPTION
**Pull request by evandrocoan**
JavaScript media support should be a great addition to Anki in cases the standard player is somehow not working:
1. https://anki.tenderapp.com/discussions/ankidesktop/41235-how-to-add-video-saved-in-my-mac-to-my-deck-or-cards
1. https://anki.tenderapp.com/discussions/ankidesktop/41438-error-on-database
1. https://anki.tenderapp.com/discussions/ankidesktop/41106-card-audio-playback-changes-bug-in-212x
1. https://anki.tenderapp.com/discussions/ankidesktop/41344-o-audio-dos-meus-flash-cards-no-esta-funcionando

The pull-request https://github.com/ankitects/anki-manual/pull/128 Created the ankimedia documentation section on src/media.md, adds documentation for this feature. The `ankimedia` object implementation and automated integration tests are split in a second repository, https://github.com/evandrocoan/AnkiMediaQueue, and shipped with Anki only the build typescript file.

### CODE REVIEW

**Comment by dae** [comment]
Thanks Evandro. I'm currently focused on backend changes, but I'll leave this around like #540 to return to at a future date when things are not so busy.

**Comment by evandrocoan** [comment]
@dae , This pull-request should be good to be merged. I updated the first post. The changes to the Anki code are minimal (hooks to control the page media). The implementation itself is all contained inside the `ankimedia` object. It would be nice if the pull-request is not squashed, as reviewing locally with git (as with the smargit tool) is way better than opening the original pull-request on GitHub).

As the whole thing is my implementation, I want you to know that I am not burdening you with maintaining it. I explained on the documentation page that this feature comes without support from the Anki team. Still, I am open to supporting this with my issue tracker on the second repository and applying pull requests to fix the code on Anki if required.

I checked, and the HTML media added still works on the Anki web version of anki (as it is just HTML). What does not work is the automatic playing of the `ankimedia` object control (as it is not included in the Anki Web version). Integrating it with the Anki web, and Android should be simple enough. Include the `ankimedia.js` and call its few hooks before showing a question as done with the anki desktop integration.

I am open to helping/maintaining any problems you may have with the use of `ankimedia` elsewhere on inside anki desktop. I think it should be pretty stable as:
1. I developed it with extensive automated testing, so all interfaces are also tested outside Anki in a vanilla chromium browser.
2. I Have been using it for the last years since I started this pull-request and have fixed many problems I encountered.

If someone misses some new integration with Anki, you can point out can look into how to integrate it. Its Javascript playback would be a pretty addition to Anki and would work as an alternative to mpv or mplayer.

**Comment by dae** [comment]
Hi Evandro,

I haven't forgotten about this, and such an API is still something that might be nice to support in the future. It's something I'd like to give a proper amount of thought and attention to before deciding on though, as despite any warnings/disclaimers you give users, once the functionality is made available, people will [depend on it](https://www.hyrumslaw.com/), and it will be difficult to make changes if we later decide that the implementation is not optimal. I'd hoped that almost 3 years later I wouldn't be feeling so swamped by the todo list, but sadly there are still too many things to do and not enough time :-(

In the mean time, is this something that could perhaps be done in an add-on? I'd be open to a PR that adds any required hooks so you don't need to monkeypatch the eval calls in.

**Comment by evandrocoan** [comment]
Hi. Thanks for looking into it. Yes, it can be added in an addon, as the integration require some hooks. As an Addon, it should give people more chances to use it before adding it to the main Anki code.

Should I close this pull request after adding the addon hooks?

**Comment by dae** [comment]
I don't mind either way - if/when I have time to explore this more deeply in the future, I can reach out whether or not the PR is open.

**Comment by dae** [comment]
Closing this now - while JS-based audio is still something I'd like to tackle at one point, it will likely require a new implementation.

**Pull request closed without merging**
